(()=>{
'use strict';
const $=s=>document.querySelector(s);
const home=$('#home'),choose=$('#choose'),filesInput=$('#files'),pasteOpen=$('#pasteOpen'),error=$('#error');
const pasteSheet=$('#pasteSheet'),pasteClose=$('#pasteClose'),pasteText=$('#pasteText'),pasteUse=$('#pasteUse'),pasteModes=$('#pasteModes');
const reader=$('#reader'),exit=$('#exit'),stage=$('#stage'),pdfCanvas=$('#pdfCanvas'),imagePage=$('#imagePage'),textPage=$('#textPage'),textBody=$('#textBody'),stepNo=$('#stepNo'),measureText=$('#measureText'),loading=$('#loading'),loadingNote=$('#loadingNote'),pctx=pdfCanvas.getContext('2d',{alpha:false});
const faceVideo=$('#faceVideo'),fileKind=$('#fileKind'),pageNow=$('#pageNow'),pageTotal=$('#pageTotal'),statusDot=$('#statusDot'),statusText=$('#statusText'),actionBtn=$('#actionBtn'),actionBtnBottom=$('#actionBtnBottom'),prevBtn=$('#prev'),nextBtn=$('#next'),edgePrev=$('#edgePrev'),edgeNext=$('#edgeNext');
const mouthDock=$('#mouthDock'),mouthPeek=$('#mouthPeek'),mouthDockText=$('#mouthDockText'),mouthCtx=mouthPeek?.getContext('2d');
const actionSheet=$('#actionSheet'),actionClose=$('#actionClose'),permission=$('#permission'),permissionTitle=$('#permissionTitle'),permissionHint=$('#permissionHint'),permissionAction=$('#permissionAction');
let kind=null,pdfjs=null,pdfDoc=null,pdfWorker='',pages=[],current=1,total=1,renderToken=0,renderTask=null,ownedUrls=[],pasteMode='pages',wake=null,pointerStart=null,resizeTimer=0;
let videoStream=null,faceLandmarker=null,frameHandle=0,rafHandle=0,lastInferAt=0,lastFaceAt=0,lastVideoTime=-1,inferenceBusy=false,frameCounter=0;
let base=null,baseReady=false,baseSamples=[],smooth=null,release={pucker:true,open:true},lastFireAt=0,shake=null,lastYaw=0,lastPitch=0,lastPoseAt=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
const mad=(a,m=median(a))=>median(a.map(v=>Math.abs(v-m)));
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function setError(t=''){error.hidden=!t;error.textContent=t}
function setLoading(on,note='请稍候'){loading.hidden=!on;loadingNote.textContent=note}
function own(url){ownedUrls.push(url);return url}
function clearOwned(){for(const u of ownedUrls)URL.revokeObjectURL(u);ownedUrls=[]}
function setStatus(text,live=false,hit=false){statusText.textContent=text;statusDot.classList.toggle('live',live);statusDot.classList.toggle('hit',hit)}
function defaultStatus(){setStatus(videoStream?'嘟嘴 / 点头向前 · 张嘴 / 摇头返回':'无声操作未开启',!!videoStream,false)}
async function requestWake(){if(document.hidden||wake||!navigator.wakeLock?.request)return;try{wake=await navigator.wakeLock.request('screen');wake.addEventListener?.('release',()=>wake=null,{once:true})}catch{}}
async function releaseWake(){const w=wake;wake=null;if(w)try{await w.release()}catch{}}
async function loadPdfLibrary(){if(pdfjs)return pdfjs;const sources=[{main:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.mjs',worker:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.worker.mjs'},{main:'https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.mjs',worker:'https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.worker.mjs'}];let last=null;for(const s of sources){try{pdfjs=await import(s.main);pdfWorker=s.worker;break}catch(e){last=e}}if(!pdfjs)throw last||new Error('pdfjs');pdfjs.GlobalWorkerOptions.workerSrc=pdfWorker;return pdfjs}
async function loadZip(){const urls=['https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm','https://esm.sh/jszip@3.10.1'];let last=null;for(const u of urls){try{const m=await import(u);return m.default||m}catch(e){last=e}}throw last||new Error('zip')}
function resolvePath(base,rel){if(/^([a-z]+:|\/)/i.test(rel))return rel;const parts=base.split('/').slice(0,-1).concat(rel.split('/')),out=[];for(const p of parts){if(!p||p==='.')continue;if(p==='..')out.pop();else out.push(p)}return out.join('/')}
function markdownBlocks(text){const lines=String(text).replace(/\r/g,'').split('\n'),blocks=[];let para=[],list=null;const inline=s=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');const flush=()=>{if(para.length){blocks.push(`<p>${inline(para.join(' '))}</p>`);para=[]}};const close=()=>{if(list){blocks.push(`<${list.tag}>${list.items.map(x=>`<li>${inline(x)}</li>`).join('')}</${list.tag}>`);list=null}};for(const raw of lines){const line=raw.trim();if(!line){flush();close();continue}let m=line.match(/^(#{1,3})\s+(.+)$/);if(m){flush();close();blocks.push(`<h${m[1].length}>${inline(m[2])}</h${m[1].length}>`);continue}m=line.match(/^>\s*(.+)$/);if(m){flush();close();blocks.push(`<blockquote>${inline(m[1])}</blockquote>`);continue}m=line.match(/^[-*•]\s+(.+)$/);if(m){flush();if(!list||list.tag!=='ul'){close();list={tag:'ul',items:[]}}list.items.push(m[1]);continue}m=line.match(/^\d+[.)、]\s*(.+)$/);if(m){flush();if(!list||list.tag!=='ol'){close();list={tag:'ol',items:[]}}list.items.push(m[1]);continue}para.push(line)}flush();close();return blocks}
function stepBlocks(text){const lines=String(text).replace(/\r/g,'').split('\n'),steps=[];let cur=[];const push=()=>{const s=cur.join('\n').trim();if(s)steps.push(s);cur=[]};for(const raw of lines){const line=raw.trim();if(!line){if(cur.length)push();continue}if(/^(?:\d+[.)、]|[-*•]|第\s*\d+\s*步)/.test(line)){if(cur.length)push();cur=[line.replace(/^(?:\d+[.)、]|[-*•])\s*/,'')]}else cur.push(line)}push();return steps.length>=2?steps:String(text).split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean)}
function setMeasureWidth(){const r=stage.getBoundingClientRect();measureText.style.width=`${Math.max(240,Math.min(740,r.width-40))}px`;measureText.style.maxHeight=`${Math.max(260,r.height-40)}px`}
function paginateBlocks(blocks){setMeasureWidth();const maxH=Math.max(220,stage.getBoundingClientRect().height-72),made=[];let cur=[];for(const b of blocks){cur.push(b);measureText.innerHTML=cur.join('');if(measureText.scrollHeight>maxH&&cur.length>1){cur.pop();made.push(cur.join(''));cur=[b]}}if(cur.length)made.push(cur.join(''));return made.length?made:['<p>没有可显示的文字。</p>']}
async function openText(text,mode='pages',label='文字'){reader.hidden=false;home.hidden=true;kind=mode==='steps'?'steps':'text';fileKind.textContent=mode==='steps'?'下一步':label;pages=mode==='steps'?stepBlocks(text).map((s,i)=>({html:`<div>${markdownBlocks(s).join('')}</div>`,step:i+1})):paginateBlocks(markdownBlocks(text)).map(html=>({html}));total=pages.length;current=1;pageTotal.textContent=String(total);await showPage(1);await ensureSilent(true);requestWake()}
async function openEpub(file){setLoading(true,'正在读取 EPUB');const JSZip=await loadZip(),zip=await JSZip.loadAsync(await file.arrayBuffer());const container=await zip.file('META-INF/container.xml')?.async('text');if(!container)throw new Error('epub');const root=new DOMParser().parseFromString(container,'application/xml').querySelector('rootfile')?.getAttribute('full-path');if(!root)throw new Error('epub');const opfText=await zip.file(root)?.async('text');if(!opfText)throw new Error('epub');const opf=new DOMParser().parseFromString(opfText,'application/xml'),items={};opf.querySelectorAll('item').forEach(i=>items[i.getAttribute('id')]={href:i.getAttribute('href')});const blocks=[];for(const ir of opf.querySelectorAll('spine itemref')){const it=items[ir.getAttribute('idref')];if(!it?.href)continue;const x=await zip.file(resolvePath(root,it.href))?.async('text');if(!x)continue;const doc=new DOMParser().parseFromString(x,'text/html');doc.querySelectorAll('script,style,nav').forEach(n=>n.remove());for(const n of doc.body.querySelectorAll('h1,h2,h3,p,li,blockquote')){const t=n.textContent.trim();if(!t)continue;const tag=/^H[123]$/.test(n.tagName)?n.tagName.toLowerCase():n.tagName==='LI'?'li':n.tagName==='BLOCKQUOTE'?'blockquote':'p';blocks.push(`<${tag}>${esc(t)}</${tag}>`)}}reader.hidden=false;home.hidden=true;kind='text';fileKind.textContent='EPUB';pages=paginateBlocks(blocks).map(html=>({html}));total=pages.length;current=1;pageTotal.textContent=String(total);setLoading(false);await showPage(1);await ensureSilent(true);requestWake()}
function loadImage(url){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url})}
function toBlob(canvas,type='image/jpeg'){return new Promise((ok,no)=>canvas.toBlob(b=>b?ok(b):no(new Error('blob')),type,type==='image/jpeg'?.94:undefined))}
async function imagePages(files){const sorted=[...files].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})),out=[];for(const file of sorted){const url=own(URL.createObjectURL(file)),img=await loadImage(url),w=img.naturalWidth,h=img.naturalHeight;if(h>w*2.15&&window.LONG_CUTTER){const cuts=LONG_CUTTER.find(img,w,h,1.68),bounds=[0,...cuts,h];for(let i=0;i<bounds.length-1;i++){const y=Math.round(bounds[i]),hh=Math.max(1,Math.round(bounds[i+1])-y),c=document.createElement('canvas');c.width=w;c.height=hh;c.getContext('2d').drawImage(img,0,y,w,hh,0,0,w,hh);const b=await toBlob(c,file.type==='image/png'?'image/png':'image/jpeg');out.push({url:own(URL.createObjectURL(b))})}}else out.push({url})}return out}
async function openFiles(list){setError('');const fs=[...list];if(!fs.length)return;clearOwned();cleanupSilent();try{const pdfs=fs.filter(f=>f.type==='application/pdf'||/\.pdf$/i.test(f.name)),epubs=fs.filter(f=>/\.epub$/i.test(f.name)),texts=fs.filter(f=>f.type.startsWith('text/')||/\.(txt|md|markdown)$/i.test(f.name)),imgs=fs.filter(f=>f.type.startsWith('image/'));if([pdfs.length>0,epubs.length>0,texts.length>0,imgs.length>0].filter(Boolean).length>1)throw new Error('mixed');reader.hidden=false;home.hidden=true;setLoading(true,'正在打开内容');if(pdfs.length){if(pdfs.length>1)throw new Error('onepdf');kind='pdf';fileKind.textContent='PDF';const lib=await loadPdfLibrary(),data=new Uint8Array(await pdfs[0].arrayBuffer());pdfDoc=await lib.getDocument({data}).promise;total=pdfDoc.numPages;pages=[]}else if(epubs.length){if(epubs.length>1)throw new Error('oneepub');await openEpub(epubs[0]);return}else if(texts.length){const text=(await Promise.all(texts.map(f=>f.text()))).join('\n\n');setLoading(false);await openText(text,'pages','文字');return}else if(imgs.length){kind='images';fileKind.textContent='图片';pages=await imagePages(imgs);total=pages.length}else throw new Error('unsupported');current=1;pageTotal.textContent=String(total);setLoading(false);await showPage(1);await ensureSilent(true);requestWake()}catch(e){console.error(e);await closeReader();setError(e?.message==='mixed'?'不同类型请分开打开。':e?.message==='onepdf'?'一次先打开一个 PDF。':e?.message==='oneepub'?'一次先打开一本 EPUB。':'这个内容没有成功打开。')}}
async function showPage(n,flashDir=null){if(!kind)return;current=clamp(n,1,total);pageNow.textContent=String(current);prevBtn.disabled=current<=1;nextBtn.disabled=current>=total;if(flashDir)flashEdge(flashDir);pdfCanvas.hidden=true;imagePage.hidden=true;textPage.hidden=true;stepNo.hidden=true;if(kind==='images'){imagePage.src=pages[current-1].url;imagePage.hidden=false;try{await imagePage.decode()}catch{}return}if(kind==='text'||kind==='steps'){textBody.innerHTML=pages[current-1].html;textPage.hidden=false;textPage.classList.toggle('step-page',kind==='steps');if(kind==='steps'){stepNo.hidden=false;stepNo.textContent=String(current).padStart(2,'0')}return}const token=++renderToken;try{renderTask?.cancel()}catch{}renderTask=null;const page=await pdfDoc.getPage(current);if(token!==renderToken)return;const baseVp=page.getViewport({scale:1}),r=stage.getBoundingClientRect(),fit=Math.min(Math.max(120,r.width-8)/baseVp.width,Math.max(120,r.height-8)/baseVp.height),dpr=Math.min(2,window.devicePixelRatio||1),vp=page.getViewport({scale:fit*dpr});pdfCanvas.width=Math.max(1,Math.round(vp.width));pdfCanvas.height=Math.max(1,Math.round(vp.height));pdfCanvas.style.width=`${vp.width/dpr}px`;pdfCanvas.style.height=`${vp.height/dpr}px`;pctx.fillStyle='#fff';pctx.fillRect(0,0,pdfCanvas.width,pdfCanvas.height);pdfCanvas.hidden=false;renderTask=page.render({canvasContext:pctx,viewport:vp});try{await renderTask.promise}catch(e){if(e?.name!=='RenderingCancelledException')throw e}finally{if(token===renderToken)renderTask=null}}
function flashEdge(dir){const el=dir==='prev'?edgePrev:edgeNext;el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),120)}
function nextPage(){if(current<total)showPage(current+1,'next');else flashEdge('next')}
function prevPage(){if(current>1)showPage(current-1,'prev');else flashEdge('prev')}
function dist(a,b){return Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0))}
function blendMap(result){const cats=result?.faceBlendshapes?.[0]?.categories||[],m={};for(const c of cats){const k=String(c.categoryName||c.displayName||'').replace(/[_\s-]/g,'').toLowerCase();m[k]=Number(c.score)||0}return{pucker:m.mouthpucker||0,funnel:m.mouthfunnel||0,jaw:m.jawopen||0,smile:Math.max(m.mouthsmileleft||0,m.mouthsmileright||0),stretch:Math.max(m.mouthstretchleft||0,m.mouthstretchright||0)}}
function metrics(r){const lm=r?.faceLandmarks?.[0];if(!lm?.length)return null;const L=lm[234],R=lm[454],T=lm[10],C=lm[152],N=lm[1],ml=lm[61],mr=lm[291],mu=lm[13],md=lm[14];if(!L||!R||!T||!C||!N||!ml||!mr||!mu||!md)return null;const fw=Math.max(.001,dist(L,R)),fh=Math.max(.001,dist(T,C)),mw=Math.max(.001,dist(ml,mr)),gap=dist(mu,md),b=blendMap(r);return{yaw:(N.x-(L.x+R.x)/2)/fw,pitch:(N.y-(T.y+C.y)/2)/fh,openGeo:gap/mw,mouthWidth:mw/fw,puckerBlend:Math.max(b.pucker,b.funnel*.92)-b.jaw*.18-Math.max(b.smile,b.stretch)*.12,jaw:b.jaw,scale:fw,lm}}
function smoothMetrics(m){if(!smooth){smooth={...m};return smooth}const a=.58;for(const k of ['yaw','pitch','openGeo','mouthWidth','puckerBlend','jaw','scale'])smooth[k]=smooth[k]*(1-a)+m[k]*a;smooth.lm=m.lm;return smooth}
function renderMouth(lm){if(!mouthCtx||!lm||frameCounter%3)return;const ids=[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78,61],pts=ids.map(i=>lm[i]).filter(Boolean);if(!pts.length)return;let minX=1,maxX=0,minY=1,maxY=0;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const dx=(maxX-minX)*.22+.003,dy=(maxY-minY)*.65+.003,w=mouthPeek.width,h=mouthPeek.height;minX-=dx;maxX+=dx;minY-=dy;maxY+=dy;mouthCtx.clearRect(0,0,w,h);mouthCtx.beginPath();pts.forEach((p,i)=>{const x=(p.x-minX)/(maxX-minX)*w,y=(p.y-minY)/(maxY-minY)*h;i?mouthCtx.lineTo(x,y):mouthCtx.moveTo(x,y)});mouthCtx.strokeStyle='rgba(255,255,255,.68)';mouthCtx.lineWidth=1.2;mouthCtx.lineJoin='round';mouthCtx.stroke()}
async function loadFace(){if(faceLandmarker)return faceLandmarker;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,L=mod.FaceLandmarker||mod.default?.FaceLandmarker;if(!F||!L)throw 0;const vision=await F.forVisionTasks(s.wasm);for(const delegate of ['GPU','CPU']){try{faceLandmarker=await L.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true,minFaceDetectionConfidence:.16,minFacePresenceConfidence:.16,minTrackingConfidence:.16});return faceLandmarker}catch(e){last=e;faceLandmarker=null}}}catch(e){last=e}}throw last||new Error('face')}
function resetGestureState(full=true){baseReady=false;baseSamples=[];smooth=null;release={pucker:true,open:true};shake=null;lastYaw=0;lastPitch=0;lastPoseAt=0;if(full)lastFireAt=0;mouthDock?.classList.remove('found','hit');if(mouthDockText)mouthDockText.textContent='找动作'}
function buildBase(){if(baseSamples.length<6)return false;const vals=k=>baseSamples.map(x=>x[k]);base={yaw:median(vals('yaw')),pitch:median(vals('pitch')),openGeo:median(vals('openGeo')),mouthWidth:median(vals('mouthWidth')),puckerBlend:median(vals('puckerBlend')),jaw:median(vals('jaw')),yawNoise:mad(vals('yaw')),pitchNoise:mad(vals('pitch')),openNoise:mad(vals('openGeo')),puckerNoise:mad(vals('puckerBlend'))};baseReady=true;mouthDockText.textContent='动作已锁';return true}
function fire(dir,label,now){if(now-lastFireAt<180)return;lastFireAt=now;mouthDock.classList.add('hit');setTimeout(()=>mouthDock.classList.remove('hit'),120);dir==='next'?nextPage():prevPage();setStatus(label,true,true);setTimeout(defaultStatus,300)}
function updateBase(m){if(!baseReady)return;const safe=Math.abs(m.yaw-base.yaw)<Math.max(.035,base.yawNoise*6+.015)&&Math.abs(m.pitch-base.pitch)<Math.max(.028,base.pitchNoise*6+.012)&&Math.abs(m.openGeo-base.openGeo)<Math.max(.035,base.openNoise*5+.018)&&Math.abs(m.puckerBlend-base.puckerBlend)<Math.max(.07,base.puckerNoise*5+.035);if(!safe)return;const a=.008;for(const k of ['yaw','pitch','openGeo','mouthWidth','puckerBlend','jaw'])base[k]=base[k]*(1-a)+m[k]*a}
function evaluateGesture(m,now){if(!baseReady){baseSamples.push({...m});if(baseSamples.length>=9)buildBase();return}const puckerDelta=m.puckerBlend-base.puckerBlend,openDelta=m.openGeo-base.openGeo,jawDelta=m.jaw-base.jaw,widthDrop=base.mouthWidth-m.mouthWidth;
const pT=Math.max(.095,base.puckerNoise*7+.07),pRelease=pT*.38,oT=Math.max(.075,base.openNoise*7+.055),oRelease=oT*.36;
const puckerScore=Math.max(puckerDelta,widthDrop*.95),openScore=Math.max(openDelta,jawDelta*.20);
if(puckerScore<pRelease)release.pucker=true;if(openScore<oRelease)release.open=true;
if(release.pucker&&puckerScore>pT&&openScore<oT*.72){release.pucker=false;release.open=false;fire('next','嘟嘴 · 向前',now);return}
if(release.open&&openScore>oT&&puckerScore<pT*.72){release.open=false;release.pucker=false;fire('prev','张嘴 · 返回',now);return}
const dt=lastPoseAt?Math.max(16,now-lastPoseAt):33,dy=m.yaw-lastYaw,dp=m.pitch-lastPitch,yawV=dy/dt*1000,pitchV=dp/dt*1000,yawD=m.yaw-base.yaw,pitchD=m.pitch-base.pitch;
const nodDisp=Math.max(.026,base.pitchNoise*7+.018),nodVel=Math.max(.22,base.pitchNoise*28+.12),shakeDisp=Math.max(.038,base.yawNoise*7+.024),shakeVel=Math.max(.28,base.yawNoise*30+.14);
if(now-lastFireAt>210&&Math.abs(yawD)<shakeDisp*1.25&&Math.abs(pitchD)>nodDisp&&Math.abs(pitchV)>nodVel){fire('next','点头 · 向前',now);shake=null;lastYaw=m.yaw;lastPitch=m.pitch;lastPoseAt=now;return}
if(Math.abs(yawD)>shakeDisp&&Math.abs(yawV)>shakeVel){const side=Math.sign(yawD)||1;if(!shake||now-shake.t>680)shake={side,t:now,peak:Math.abs(yawD)};else if(side!==shake.side&&Math.abs(yawD)>shakeDisp*.85){fire('prev','摇头 · 返回',now);shake=null;lastYaw=m.yaw;lastPitch=m.pitch;lastPoseAt=now;return}else shake.peak=Math.max(shake.peak,Math.abs(yawD))}else if(shake&&now-shake.t>680)shake=null;
lastYaw=m.yaw;lastPitch=m.pitch;lastPoseAt=now;updateBase(m)}
function scheduleFrame(){if(!videoStream||document.hidden)return;if('requestVideoFrameCallback' in faceVideo){frameHandle=faceVideo.requestVideoFrameCallback(processFrame)}else rafHandle=requestAnimationFrame(processFrame)}
function cancelFrame(){if(frameHandle&&'cancelVideoFrameCallback' in faceVideo){try{faceVideo.cancelVideoFrameCallback(frameHandle)}catch{}}if(rafHandle)cancelAnimationFrame(rafHandle);frameHandle=rafHandle=0}
function processFrame(now){frameHandle=rafHandle=0;if(!videoStream||document.hidden)return;scheduleFrame();if(inferenceBusy||!faceLandmarker||faceVideo.readyState<2)return;const vt=faceVideo.currentTime;if(vt===lastVideoTime)return;if(now-lastInferAt<28)return;lastVideoTime=vt;lastInferAt=now;inferenceBusy=true;try{const r=faceLandmarker.detectForVideo(faceVideo,now),raw=metrics(r);frameCounter++;if(raw){lastFaceAt=now;mouthDock.classList.add('found');const m=smoothMetrics(raw);renderMouth(m.lm);if(!baseReady)mouthDockText.textContent='正在适应';else mouthDockText.textContent='动作已锁';evaluateGesture(m,now)}else if(now-lastFaceAt>520){mouthDock.classList.remove('found');mouthDockText.textContent='找动作';if(now-lastFaceAt>1300)resetGestureState(false)}}catch(e){console.warn('face frame',e)}finally{inferenceBusy=false}}
async function setupSilent(){cleanupSilent();videoStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640,max:960},height:{ideal:480,max:720},frameRate:{ideal:30,max:30}},audio:false});faceVideo.srcObject=videoStream;await faceVideo.play();await loadFace();mouthDock.hidden=false;resetGestureState(true);lastFaceAt=performance.now();scheduleFrame();defaultStatus()}
async function ensureSilent(auto=false){if(videoStream)return;permission.hidden=true;if(auto){try{await setupSilent();return}catch(e){console.warn(e);cleanupSilent()}}permission.hidden=false;permissionTitle.textContent='开启无声翻页';permissionHint.textContent='嘟嘴或点头向前；张嘴或摇头返回。';permissionAction.textContent='开启'}
function cleanupSilent(){cancelFrame();inferenceBusy=false;if(videoStream){for(const t of videoStream.getTracks())t.stop();videoStream=null}faceVideo.srcObject=null;mouthDock.hidden=true;mouthCtx?.clearRect(0,0,mouthPeek.width,mouthPeek.height);resetGestureState(true);defaultStatus()}
async function closeReader(){cleanupSilent();await releaseWake();try{renderTask?.cancel()}catch{}renderTask=null;pdfDoc=null;kind=null;pages=[];clearOwned();reader.hidden=true;home.hidden=false;pasteSheet.hidden=true;actionSheet.hidden=true;permission.hidden=true;filesInput.value='';setLoading(false);window.scrollTo({top:0,behavior:'instant'})}
choose.onclick=()=>filesInput.click();filesInput.onchange=()=>{openFiles(filesInput.files);filesInput.value=''};pasteOpen.onclick=()=>{pasteSheet.hidden=false;pasteText.focus()};pasteClose.onclick=()=>pasteSheet.hidden=true;pasteModes.querySelectorAll('button').forEach(b=>b.onclick=()=>{pasteMode=b.dataset.mode;pasteModes.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});pasteUse.onclick=async()=>{const t=pasteText.value.trim();if(!t)return;pasteSheet.hidden=true;clearOwned();cleanupSilent();await openText(t,pasteMode,'文字')};actionBtn.onclick=()=>actionSheet.hidden=false;actionBtnBottom.onclick=()=>actionSheet.hidden=false;actionClose.onclick=()=>actionSheet.hidden=true;permissionAction.onclick=async()=>{permissionAction.disabled=true;try{await setupSilent();permission.hidden=true}catch(e){console.error(e);permissionTitle.textContent='没有准备好';permissionHint.textContent='需要允许前置相机。请让脸大致出现在镜头里，再试一次。'}finally{permissionAction.disabled=false}};prevBtn.onclick=prevPage;nextBtn.onclick=nextPage;exit.onclick=closeReader;stage.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId});stage.addEventListener('pointerup',e=>{if(!pointerStart||pointerStart.id!==e.pointerId)return;const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;pointerStart=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)(dx<0?nextPage:prevPage)()});document.addEventListener('keydown',e=>{if(reader.hidden)return;if(e.key==='ArrowRight'||e.key==='PageDown')nextPage();if(e.key==='ArrowLeft'||e.key==='PageUp')prevPage()});window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!reader.hidden&&kind==='pdf')showPage(current)},120)});document.addEventListener('visibilitychange',async()=>{if(reader.hidden)return;if(document.hidden){cancelFrame();await releaseWake()}else{await requestWake();if(videoStream){try{await faceVideo.play()}catch{}scheduleFrame()}}});window.addEventListener('pagehide',()=>{cleanupSilent();releaseWake();clearOwned()});
})();