(()=>{
  const $=s=>document.querySelector(s);
  const home=$('#home'),choose=$('#choose'),filesInput=$('#files'),pasteOpen=$('#pasteOpen'),error=$('#error');
  const pasteSheet=$('#pasteSheet'),pasteClose=$('#pasteClose'),pasteText=$('#pasteText'),pasteUse=$('#pasteUse'),pasteModes=$('#pasteModes');
  const reader=$('#reader'),exit=$('#exit'),stage=$('#stage'),pdfCanvas=$('#pdfCanvas'),imagePage=$('#imagePage'),textPage=$('#textPage'),textBody=$('#textBody'),stepNo=$('#stepNo'),measureText=$('#measureText'),loading=$('#loading'),loadingNote=$('#loadingNote'),pctx=pdfCanvas.getContext('2d',{alpha:false});
  const faceVideo=$('#faceVideo'),mouthPeek=$('#mouthPeek'),mouthDock=$('#mouthDock'),mouthDockText=$('#mouthDockText'),mouthCtx=mouthPeek?.getContext('2d',{willReadFrequently:true});
  const fileKind=$('#fileKind'),pageNow=$('#pageNow'),pageTotal=$('#pageTotal'),statusDot=$('#statusDot'),statusText=$('#statusText'),actionBtn=$('#actionBtn'),prevBtn=$('#prev'),nextBtn=$('#next'),edgePrev=$('#edgePrev'),edgeNext=$('#edgeNext');
  const actionSheet=$('#actionSheet'),actionClose=$('#actionClose'),actionOptions=$('#actionOptions'),voiceSetup=$('#voiceSetup'),voiceForward=$('#voiceForward'),voiceBack=$('#voiceBack'),voiceDone=$('#voiceDone'),voiceHint=$('#voiceHint');
  const permission=$('#permission'),permissionTitle=$('#permissionTitle'),permissionHint=$('#permissionHint'),permissionAction=$('#permissionAction');

  let kind=null,pdfjs=null,pdfDoc=null,pdfWorker='',pages=[],current=1,total=1,renderToken=0,renderTask=null,ownedUrls=[];
  let pasteMode='pages',controlMode=localStorage.getItem('handsfree-control-v6')||localStorage.getItem('handsfree-control-v5')||'blow';
  if(!['blow','voice','mouth'].includes(controlMode))controlMode='blow';
  let audioStream=null,videoStream=null,audio=null,source=null,analyser=null,timeData=null,freqData=null;
  let faceLandmarker=null,faceLoop=0,faceLast=0,faceSeenUntil=0,currentMouth={pucker:0,funnel:0,puff:0,jaw:0,key:0},idleMouth=.03;
  let ambient=.002,listening=false,monitorRaf=0,lastFrame=0,cooldownUntil=0,wake=null,pointerStart=null,resizeTimer=0,busy=false;
  let audioEvent=null,audioStarted=0,audioLast=0,mouthEvent=null,mouthStarted=0,mouthLast=0,captureDirection=null;
  let forwardTemplate=readTemplate('handsfree-forward-v6')||migrateTemplate('handsfree-forward-v5');
  let backTemplate=readTemplate('handsfree-back-v6')||migrateTemplate('handsfree-back-v5');

  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function readTemplate(k){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v&&Array.isArray(v.seq)?v:null}catch{return null}}
  function migrateTemplate(k){try{const old=JSON.parse(localStorage.getItem(k)||'null');if(!old||!Array.isArray(old.bands))return null;const seq=[];for(let t=0;t<10;t++)seq.push(...old.bands);const v={seq,envelope:new Array(10).fill(1),duration:old.duration||350,flat:old.flat||.03,centroid:.5,version:6};return v}catch{return null}}
  function saveTemplate(k,v){try{if(v)localStorage.setItem(k,JSON.stringify(v));else localStorage.removeItem(k)}catch{}}

  function setError(t=''){error.hidden=!t;error.textContent=t}
  function setLoading(on,note='请稍候'){loading.hidden=!on;loadingNote.textContent=note}
  function own(url){ownedUrls.push(url);return url}
  function clearOwned(){for(const u of ownedUrls)URL.revokeObjectURL(u);ownedUrls=[]}
  async function requestWake(){if(document.hidden||wake||!navigator.wakeLock?.request)return;try{wake=await navigator.wakeLock.request('screen');wake.addEventListener?.('release',()=>wake=null,{once:true})}catch{}}
  async function releaseWake(){const w=wake;wake=null;if(w)try{await w.release()}catch{}}
  function setStatus(text,live=false,hit=false){statusText.textContent=text;statusDot.classList.toggle('live',live);statusDot.classList.toggle('hit',hit)}
  function defaultStatus(){const t={blow:'吹一下向前',voice:backTemplate?'你的声音 · 前后都可用':'你的声音 · 向前',mouth:'嘟嘴向前 · 张嘴返回'};setStatus(t[controlMode],listening,false)}

  async function loadPdfLibrary(){
    if(pdfjs)return pdfjs;
    const sources=[
      {main:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.mjs',worker:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.worker.mjs'},
      {main:'https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.mjs',worker:'https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.worker.mjs'}
    ];
    let last=null;for(const s of sources){try{pdfjs=await import(s.main);pdfWorker=s.worker;break}catch(e){last=e}}
    if(!pdfjs)throw last||new Error('pdfjs');pdfjs.GlobalWorkerOptions.workerSrc=pdfWorker;return pdfjs
  }
  async function loadZip(){const urls=['https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm','https://esm.sh/jszip@3.10.1'];let last=null;for(const u of urls){try{const m=await import(u);return m.default||m}catch(e){last=e}}throw last||new Error('zip')}
  function resolvePath(base,rel){if(/^([a-z]+:|\/)/i.test(rel))return rel;const parts=base.split('/').slice(0,-1).concat(rel.split('/')),out=[];for(const p of parts){if(!p||p==='.')continue;if(p==='..')out.pop();else out.push(p)}return out.join('/')}

  function markdownBlocks(text){
    const lines=String(text).replace(/\r/g,'').split('\n'),blocks=[];let para=[],list=null;
    const inline=s=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
    const flush=()=>{if(para.length){blocks.push(`<p>${inline(para.join(' '))}</p>`);para=[]}};
    const closeList=()=>{if(list){blocks.push(`<${list.tag}>${list.items.map(x=>`<li>${inline(x)}</li>`).join('')}</${list.tag}>`);list=null}};
    for(const raw of lines){const line=raw.trim();if(!line){flush();closeList();continue}
      let m=line.match(/^(#{1,3})\s+(.+)$/);if(m){flush();closeList();const n=m[1].length;blocks.push(`<h${n}>${inline(m[2])}</h${n}>`);continue}
      m=line.match(/^>\s*(.+)$/);if(m){flush();closeList();blocks.push(`<blockquote>${inline(m[1])}</blockquote>`);continue}
      m=line.match(/^[-*•]\s+(.+)$/);if(m){flush();if(!list||list.tag!=='ul'){closeList();list={tag:'ul',items:[]}}list.items.push(m[1]);continue}
      m=line.match(/^\d+[.)、]\s*(.+)$/);if(m){flush();if(!list||list.tag!=='ol'){closeList();list={tag:'ol',items:[]}}list.items.push(m[1]);continue}
      para.push(line)
    }flush();closeList();return blocks
  }
  function stepBlocks(text){const lines=String(text).replace(/\r/g,'').split('\n'),steps=[];let cur=[];const push=()=>{const s=cur.join('\n').trim();if(s)steps.push(s);cur=[]};for(const raw of lines){const line=raw.trim();if(!line){if(cur.length)push();continue}if(/^(?:\d+[.)、]|[-*•]|第\s*\d+\s*步)/.test(line)){if(cur.length)push();cur=[line.replace(/^(?:\d+[.)、]|[-*•])\s*/,'')]}else cur.push(line)}push();if(steps.length<2)return String(text).split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean);return steps}
  function setMeasureWidth(){const r=stage.getBoundingClientRect();measureText.style.width=`${Math.max(240,Math.min(740,r.width-40))}px`;measureText.style.maxHeight=`${Math.max(260,r.height-40)}px`}
  function paginateBlocks(blocks){setMeasureWidth();const maxH=Math.max(220,stage.getBoundingClientRect().height-72),made=[];let cur=[];for(const b of blocks){cur.push(b);measureText.innerHTML=cur.join('');if(measureText.scrollHeight>maxH&&cur.length>1){cur.pop();made.push(cur.join(''));cur=[b]}}if(cur.length)made.push(cur.join(''));return made.length?made:['<p>没有可显示的文字。</p>']}
  async function openText(text,mode='pages',label='文字'){reader.hidden=false;home.hidden=true;kind=mode==='steps'?'steps':'text';fileKind.textContent=mode==='steps'?'下一步':label;pages=mode==='steps'?stepBlocks(text).map((s,i)=>({html:`<div>${markdownBlocks(s).join('')}</div>`,step:i+1})):paginateBlocks(markdownBlocks(text)).map(html=>({html}));total=pages.length;current=1;pageTotal.textContent=String(total);await showPage(1);await prepareControl(controlMode,true);requestWake()}
  async function openEpub(file){
    setLoading(true,'正在读取 EPUB');const JSZip=await loadZip(),zip=await JSZip.loadAsync(await file.arrayBuffer());const container=await zip.file('META-INF/container.xml')?.async('text');if(!container)throw new Error('epub');const cx=new DOMParser().parseFromString(container,'application/xml'),root=cx.querySelector('rootfile')?.getAttribute('full-path');if(!root)throw new Error('epub');
    const opfText=await zip.file(root)?.async('text');if(!opfText)throw new Error('epub');const opf=new DOMParser().parseFromString(opfText,'application/xml'),items={};opf.querySelectorAll('item').forEach(i=>items[i.getAttribute('id')]={href:i.getAttribute('href'),type:i.getAttribute('media-type')});
    const blocks=[];for(const ir of opf.querySelectorAll('spine itemref')){const it=items[ir.getAttribute('idref')];if(!it?.href)continue;const path=resolvePath(root,it.href),x=await zip.file(path)?.async('text');if(!x)continue;const doc=new DOMParser().parseFromString(x,'text/html');doc.querySelectorAll('script,style,nav').forEach(n=>n.remove());const nodes=[...doc.body.querySelectorAll('h1,h2,h3,p,li,blockquote')];if(nodes.length){for(const n of nodes){const t=n.textContent.trim();if(!t)continue;const tag=/^H[123]$/.test(n.tagName)?n.tagName.toLowerCase():n.tagName==='LI'?'li':n.tagName==='BLOCKQUOTE'?'blockquote':'p';blocks.push(`<${tag}>${esc(t)}</${tag}>`)}}else{const t=doc.body.textContent.trim();if(t)blocks.push(`<p>${esc(t)}</p>`)}}
    reader.hidden=false;home.hidden=true;kind='text';fileKind.textContent='EPUB';pages=paginateBlocks(blocks).map(html=>({html}));total=pages.length;current=1;pageTotal.textContent=String(total);setLoading(false);await showPage(1);await prepareControl(controlMode,true);requestWake()
  }
  function loadImage(url){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url})}
  function toBlob(canvas,type='image/jpeg'){return new Promise((ok,no)=>canvas.toBlob(b=>b?ok(b):no(new Error('blob')),type,type==='image/jpeg'?.94:undefined))}
  async function imagePages(files){const sorted=[...files].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})),out=[];for(const file of sorted){const url=own(URL.createObjectURL(file)),img=await loadImage(url),w=img.naturalWidth,h=img.naturalHeight;if(h>w*2.15&&window.LONG_CUTTER){const cuts=LONG_CUTTER.find(img,w,h,1.68),bounds=[0,...cuts,h];for(let i=0;i<bounds.length-1;i++){const y=Math.round(bounds[i]),hh=Math.max(1,Math.round(bounds[i+1])-y),c=document.createElement('canvas');c.width=w;c.height=hh;c.getContext('2d').drawImage(img,0,y,w,hh,0,0,w,hh);const b=await toBlob(c,file.type==='image/png'?'image/png':'image/jpeg');out.push({type:'image',url:own(URL.createObjectURL(b))})}}else out.push({type:'image',url})}return out}
  async function openFiles(list){setError('');const files=[...list];if(!files.length)return;clearOwned();cleanupControl();try{const pdfs=files.filter(f=>f.type==='application/pdf'||/\.pdf$/i.test(f.name)),epubs=files.filter(f=>/\.epub$/i.test(f.name)),texts=files.filter(f=>f.type.startsWith('text/')||/\.(txt|md|markdown)$/i.test(f.name)),imgs=files.filter(f=>f.type.startsWith('image/'));if([pdfs.length>0,epubs.length>0,texts.length>0,imgs.length>0].filter(Boolean).length>1)throw new Error('mixed');reader.hidden=false;home.hidden=true;setLoading(true,'正在打开内容');if(pdfs.length){if(pdfs.length>1)throw new Error('onepdf');kind='pdf';fileKind.textContent='PDF';const lib=await loadPdfLibrary(),data=new Uint8Array(await pdfs[0].arrayBuffer());pdfDoc=await lib.getDocument({data}).promise;total=pdfDoc.numPages;pages=[]}else if(epubs.length){if(epubs.length>1)throw new Error('oneepub');await openEpub(epubs[0]);return}else if(texts.length){const text=(await Promise.all(texts.map(f=>f.text()))).join('\n\n');setLoading(false);await openText(text,'pages','文字');return}else if(imgs.length){kind='images';fileKind.textContent='图片';pages=await imagePages(imgs);total=pages.length}else throw new Error('unsupported');current=1;pageTotal.textContent=String(total);setLoading(false);await showPage(1);await prepareControl(controlMode,true);requestWake()}catch(e){console.error(e);await closeReader();setError(e?.message==='mixed'?'不同类型请分开打开。':e?.message==='onepdf'?'一次先打开一个 PDF。':e?.message==='oneepub'?'一次先打开一本 EPUB。':'这个内容没有成功打开。')}}

  async function showPage(n,flashDir=null){if(!kind)return;current=clamp(n,1,total);pageNow.textContent=String(current);prevBtn.disabled=current<=1;nextBtn.disabled=current>=total;if(flashDir)flashEdge(flashDir);pdfCanvas.hidden=true;imagePage.hidden=true;textPage.hidden=true;stepNo.hidden=true;if(kind==='images'){imagePage.src=pages[current-1].url;imagePage.hidden=false;try{await imagePage.decode()}catch{}return}if(kind==='text'||kind==='steps'){textBody.innerHTML=pages[current-1].html;textPage.hidden=false;textPage.classList.toggle('step-page',kind==='steps');if(kind==='steps'){stepNo.hidden=false;stepNo.textContent=String(current).padStart(2,'0')}return}const token=++renderToken;try{renderTask?.cancel()}catch{}renderTask=null;const page=await pdfDoc.getPage(current);if(token!==renderToken)return;const base=page.getViewport({scale:1}),r=stage.getBoundingClientRect(),maxW=Math.max(120,r.width-8),maxH=Math.max(120,r.height-8),fit=Math.min(maxW/base.width,maxH/base.height),dpr=Math.min(2,window.devicePixelRatio||1),vp=page.getViewport({scale:fit*dpr});pdfCanvas.width=Math.max(1,Math.round(vp.width));pdfCanvas.height=Math.max(1,Math.round(vp.height));pdfCanvas.style.width=`${vp.width/dpr}px`;pdfCanvas.style.height=`${vp.height/dpr}px`;pctx.fillStyle='#fff';pctx.fillRect(0,0,pdfCanvas.width,pdfCanvas.height);pdfCanvas.hidden=false;renderTask=page.render({canvasContext:pctx,viewport:vp});try{await renderTask.promise}catch(e){if(e?.name!=='RenderingCancelledException')throw e}finally{if(token===renderToken)renderTask=null}}
  function flashEdge(dir){const el=dir==='prev'?edgePrev:edgeNext;el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),220)}
  function nextPage(){if(current<total)showPage(current+1,'next');else{flashEdge('next');setStatus('已经是最后一页',true,true);setTimeout(defaultStatus,650)}}
  function prevPage(){if(current>1)showPage(current-1,'prev');else{flashEdge('prev');setStatus('已经是第一页',true,true);setTimeout(defaultStatus,650)}}

  function audioFeature(){
    if(!analyser)return{rms:0,flat:0,centroid:0,bands:new Array(16).fill(0)};
    analyser.getFloatTimeDomainData(timeData);let s=0;for(const v of timeData)s+=v*v;const rms=Math.sqrt(s/timeData.length);
    analyser.getFloatFrequencyData(freqData);const ny=audio.sampleRate/2,binHz=ny/freqData.length,edges=[70,110,170,250,360,500,700,950,1250,1650,2150,2800,3600,4600,5800,7200,9000],bands=new Array(16).fill(0),counts=new Array(16).fill(0);let logSum=0,arith=0,n=0,weighted=0,totalP=0;
    for(let i=1;i<freqData.length;i++){const hz=i*binHz;if(hz<70||hz>9000)continue;const p=Math.pow(10,freqData[i]/10);let b=0;while(b<15&&hz>=edges[b+1])b++;bands[b]+=p;counts[b]++;logSum+=Math.log(p+1e-18);arith+=p;weighted+=hz*p;totalP+=p;n++}
    let sumBands=0;for(let i=0;i<16;i++){bands[i]/=Math.max(1,counts[i]);sumBands+=bands[i]}for(let i=0;i<16;i++)bands[i]/=(sumBands+1e-18);
    const flat=n?Math.exp(logSum/n)/(arith/n+1e-18):0,centroid=totalP?weighted/totalP/9000:0;return{rms,flat,centroid,bands}
  }
  function cosine(a,b){let d=0,aa=0,bb=0;for(let i=0;i<Math.min(a.length,b.length);i++){d+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return d/Math.sqrt((aa||1)*(bb||1))}
  function resampleFrames(frames,bins=12){if(!frames.length)return{seq:[],envelope:[]};const seq=[],envelope=[];const maxR=Math.max(...frames.map(f=>f.rms),1e-6);for(let t=0;t<bins;t++){const a=Math.floor(t*frames.length/bins),b=Math.max(a+1,Math.floor((t+1)*frames.length/bins)),slice=frames.slice(a,b),v=new Array(16).fill(0);let env=0;for(const f of slice){for(let i=0;i<16;i++)v[i]+=f.bands[i];env+=f.rms/maxR}for(let i=0;i<16;i++)v[i]/=slice.length;const z=v.reduce((x,y)=>x+y,0)||1;for(let i=0;i<16;i++)seq.push(v[i]/z);envelope.push(env/slice.length)}return{seq,envelope}}
  function summarizeAudio(frames,duration=0){if(!frames.length)return null;const rs=resampleFrames(frames,12);return{seq:rs.seq,envelope:rs.envelope,duration,flat:median(frames.map(x=>x.flat)),centroid:median(frames.map(x=>x.centroid)),rms:median([...frames].sort((a,b)=>b.rms-a.rms).slice(0,Math.max(2,Math.ceil(frames.length*.4))).map(x=>x.rms)),version:6}}
  function templateScore(sample,tpl){if(!sample||!tpl||!sample.seq?.length||!tpl.seq?.length)return 0;const temporal=cosine(sample.seq,tpl.seq),env=cosine(sample.envelope||[],tpl.envelope||[]),dur=Math.min(sample.duration/tpl.duration,tpl.duration/sample.duration),flat=Math.min((sample.flat+.006)/(tpl.flat+.006),(tpl.flat+.006)/(sample.flat+.006)),cent=1-Math.min(1,Math.abs((sample.centroid||0)-(tpl.centroid||0))/.34);return temporal*.62+env*.12+clamp(dur,0,1)*.12+clamp(flat,0,1)*.07+clamp(cent,0,1)*.07}

  function mapBlend(result){const cats=result?.faceBlendshapes?.[0]?.categories||[],m={};for(const c of cats){const k=String(c.categoryName||c.displayName||'').replace(/[_\s-]/g,'').toLowerCase();m[k]=Number(c.score)||0}const pucker=m.mouthpucker||0,funnel=m.mouthfunnel||0,puff=m.cheekpuff||0,jaw=m.jawopen||0,key=Math.max(pucker,funnel*.95,puff*.78,jaw*.55);return{pucker,funnel,puff,jaw,key}}
  function renderMouthPeek(landmarks){if(!mouthCtx||!landmarks?.length||faceVideo.readyState<2)return;const ids=[0,13,14,17,61,78,82,87,88,95,291,308,312,317,318,324],pts=ids.map(i=>landmarks[i]).filter(Boolean);if(!pts.length)return;let minX=1,maxX=0,minY=1,maxY=0;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const vw=faceVideo.videoWidth,vh=faceVideo.videoHeight,cx=(minX+maxX)/2,cy=(minY+maxY)/2,bw=Math.max(.16,(maxX-minX)*2.6),bh=Math.max(.09,(maxY-minY)*2.4),sx=clamp((cx-bw/2)*vw,0,vw-2),sy=clamp((cy-bh/2)*vh,0,vh-2),sw=Math.min(bw*vw,vw-sx),sh=Math.min(bh*vh,vh-sy);mouthCtx.clearRect(0,0,mouthPeek.width,mouthPeek.height);mouthCtx.drawImage(faceVideo,sx,sy,sw,sh,0,0,mouthPeek.width,mouthPeek.height);const im=mouthCtx.getImageData(0,0,mouthPeek.width,mouthPeek.height),d=im.data,w=mouthPeek.width,h=mouthPeek.height,gray=new Uint8Array(w*h);for(let i=0,j=0;i<d.length;i+=4,j++)gray[j]=(d[i]*77+d[i+1]*150+d[i+2]*29)>>8;for(let y=0;y<h;y++){for(let x=0;x<w;x++){const j=y*w+x,i=j*4;if(x===0||y===0||x===w-1||y===h-1){d[i]=d[i+1]=d[i+2]=12;d[i+3]=255;continue}const gx=Math.abs(gray[j+1]-gray[j-1]),gy=Math.abs(gray[j+w]-gray[j-w]),e=clamp((gx+gy-12)*5,0,235);d[i]=d[i+1]=d[i+2]=e+12;d[i+3]=255}}mouthCtx.putImageData(im,0,0)}
  async function loadFace(){if(faceLandmarker)return faceLandmarker;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,L=mod.FaceLandmarker||mod.default?.FaceLandmarker;if(!F||!L)throw 0;const vision=await F.forVisionTasks(s.wasm);faceLandmarker=await L.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true,minFaceDetectionConfidence:.30,minFacePresenceConfidence:.30,minTrackingConfidence:.30});return faceLandmarker}catch(e){last=e;faceLandmarker=null}}throw last||new Error('face')}
  function startFaceLoop(){cancelAnimationFrame(faceLoop);faceLast=0;const loop=now=>{faceLoop=requestAnimationFrame(loop);if(!videoStream||!faceLandmarker||faceVideo.readyState<2||document.hidden||now-faceLast<90)return;faceLast=now;try{const r=faceLandmarker.detectForVideo(faceVideo,now);if(r?.faceBlendshapes?.length){currentMouth=mapBlend(r);faceSeenUntil=now+720;mouthDock.classList.add('found');mouthDockText.textContent='口型已锁';renderMouthPeek(r.faceLandmarks?.[0])}else if(now>faceSeenUntil){mouthDock.classList.remove('found');mouthDockText.textContent='找口型'}}catch{}};faceLoop=requestAnimationFrame(loop)}
  async function setupVideo(){videoStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:480},height:{ideal:360}},audio:false});faceVideo.srcObject=videoStream;await faceVideo.play();await loadFace();mouthDock.hidden=false;startFaceLoop();const vals=[],t0=performance.now();while(performance.now()-t0<650){vals.push(currentMouth.key);await sleep(40)}idleMouth=median(vals)||.03}
  async function setupAudio(){audioStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('audio');audio=new AC({latencyHint:'interactive'});await audio.resume();source=audio.createMediaStreamSource(audioStream);analyser=audio.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.045;source.connect(analyser);timeData=new Float32Array(analyser.fftSize);freqData=new Float32Array(analyser.frequencyBinCount);const vals=[],t0=performance.now();while(performance.now()-t0<520){vals.push(audioFeature().rms);await sleep(32)}ambient=Math.max(.0007,median(vals)||.002)}
  function cleanupControl(){listening=false;captureDirection=null;cancelAnimationFrame(monitorRaf);monitorRaf=0;cancelAnimationFrame(faceLoop);faceLoop=0;audioEvent=null;mouthEvent=null;if(source){try{source.disconnect()}catch{}source=null}if(analyser){try{analyser.disconnect()}catch{}analyser=null}if(audioStream){audioStream.getTracks().forEach(t=>t.stop());audioStream=null}if(videoStream){videoStream.getTracks().forEach(t=>t.stop());videoStream=null}faceVideo.srcObject=null;if(audio){try{audio.close()}catch{}audio=null}timeData=null;freqData=null;mouthDock.hidden=true;mouthDock.classList.remove('found');if(mouthCtx)mouthCtx.clearRect(0,0,mouthPeek.width,mouthPeek.height);setStatus('免手操作未开启',false,false)}

  function faceAvailable(){return performance.now()<faceSeenUntil}
  function puckerNow(){return Math.max(currentMouth.pucker,currentMouth.funnel*.94,currentMouth.puff*.64)}
  function jawNow(){return currentMouth.jaw||0}
  function startAudioEvent(now,f){audioEvent=[f];audioStarted=now;audioLast=now}
  function extendAudioEvent(now,f){audioLast=now;audioEvent.push(f)}
  function isBlow(sample){if(!sample)return false;const bins=sample.seq||[],high=[];for(let t=0;t<12;t++){let s=0;for(let i=9;i<16;i++)s+=bins[t*16+i]||0;high.push(s)}const highMean=high.reduce((a,b)=>a+b,0)/Math.max(1,high.length),durOK=sample.duration>=75&&sample.duration<=850,broad=sample.flat>.045||highMean>.32;return durOK&&broad&&sample.rms>=Math.max(.0038,ambient*1.9)&&!(sample.duration<115&&sample.flat<.03)}
  function finishAudioEvent(now){const sample=summarizeAudio(audioEvent,audioLast-audioStarted);audioEvent=null;if(captureDirection){if(sample&&sample.duration>=70&&sample.duration<=1800){const key=captureDirection==='forward'?'handsfree-forward-v6':'handsfree-back-v6';if(captureDirection==='forward')forwardTemplate=sample;else backTemplate=sample;saveTemplate(key,sample);navigator.vibrate?.(14);voiceHint.textContent=captureDirection==='forward'?'向前声已经记住，以后换内容也会继续用。':'返回声也记住了。';refreshVoiceButtons();captureDirection=null;listening=false;setTimeout(()=>{voiceSetup.hidden=false;actionSheet.hidden=false},150)}return}
    if(now<cooldownUntil||!sample)return;
    if(controlMode==='blow'){if(isBlow(sample)){nextPage();cooldownUntil=now+420;setStatus('吹气 · 向前',true,true);setTimeout(defaultStatus,560)}return}
    if(controlMode==='voice'){
      const sf=templateScore(sample,forwardTemplate),sb=templateScore(sample,backTemplate),cut=.875;
      if(backTemplate&&sb>=cut&&sb>sf+.035){prevPage();cooldownUntil=now+500;setStatus('返回声 · 返回',true,true);setTimeout(defaultStatus,560)}
      else if(forwardTemplate&&sf>=cut&&(!backTemplate||sf>=sb+.012)){nextPage();cooldownUntil=now+500;setStatus('向前声 · 向前',true,true);setTimeout(defaultStatus,560)}
      else if(Math.max(sf,sb)>.74){setStatus('听到了，但不像已记住的声音',true,false);setTimeout(defaultStatus,650)}
    }
  }
  function finishMouthEvent(now,type){const d=mouthLast-mouthStarted;mouthEvent=null;if(now<cooldownUntil||d<95)return;if(type==='pucker'&&controlMode==='mouth'){nextPage();cooldownUntil=now+430;setStatus('嘟嘴 · 向前',true,true);setTimeout(defaultStatus,560)}else if(type==='jaw'&&controlMode==='mouth'){prevPage();cooldownUntil=now+460;setStatus('张嘴 · 返回',true,true);setTimeout(defaultStatus,560)}}
  function controlLoop(){cancelAnimationFrame(monitorRaf);lastFrame=0;audioEvent=null;mouthEvent=null;const loop=now=>{monitorRaf=requestAnimationFrame(loop);if(!listening||now-lastFrame<28)return;lastFrame=now;const f=analyser?audioFeature():null;if(f){const gate=Math.max(.0028,ambient*1.58+.00038),active=f.rms>=gate;if(active){if(!audioEvent)startAudioEvent(now,f);else extendAudioEvent(now,f)}else if(audioEvent&&now-audioLast>135)finishAudioEvent(now);else if(!audioEvent&&f.rms<Math.max(.01,gate*.62))ambient=ambient*.996+f.rms*.004}
      if(controlMode==='mouth'&&faceAvailable()){const p=puckerNow(),j=jawNow(),pOn=p>Math.max(.14,idleMouth+.065),jOn=j>.30;if(!mouthEvent){if(jOn){mouthEvent='jaw';mouthStarted=mouthLast=now}else if(pOn){mouthEvent='pucker';mouthStarted=mouthLast=now}}else if(mouthEvent==='pucker'){if(pOn)mouthLast=now;else if(now-mouthLast>115)finishMouthEvent(now,'pucker')}else if(mouthEvent==='jaw'){if(jOn)mouthLast=now;else if(now-mouthLast>115)finishMouthEvent(now,'jaw')}}
    };monitorRaf=requestAnimationFrame(loop)}

  async function setupForMode(mode){cleanupControl();if(mode==='mouth')await setupVideo();else await setupAudio();listening=true;cooldownUntil=performance.now()+420;defaultStatus();controlLoop()}
  async function tryAutoActivate(mode){try{await setupForMode(mode);permission.hidden=true;if(mode==='voice'&&!forwardTemplate){openVoiceSetup()}return true}catch{cleanupControl();return false}}
  async function prepareControl(mode,auto=false){controlMode=mode;localStorage.setItem('handsfree-control-v6',mode);cleanupControl();actionSheet.hidden=true;permission.hidden=true;if(auto){const ok=await tryAutoActivate(mode);if(ok)return}
    permission.hidden=false;permissionTitle.textContent=mode==='blow'?'吹一下向前':mode==='voice'?'用你自己的声音':'不用出声也能翻';permissionHint.textContent=mode==='blow'?'只开麦克风，不开相机。吹气负责向前，返回仍可用左箭头。':mode==='voice'?(forwardTemplate?'你录过的声音已经保留，开启后直接继续用。':'只录一次向前声；返回声可选。以后换内容不需要重录。'):'只有这个模式会开前置相机；画面只显示一个小小的口型轮廓窗，不显示整张脸。';permissionAction.textContent='开启';permission.dataset.mode=mode}
  async function activateMode(mode){if(busy)return;busy=true;permissionAction.disabled=true;try{setStatus('正在准备',false,false);await setupForMode(mode);permission.hidden=true;if(mode==='voice'&&!forwardTemplate)openVoiceSetup()}catch(e){console.error(e);cleanupControl();permissionTitle.textContent='没有准备好';permissionHint.textContent=mode==='mouth'?'需要前置相机权限。':'需要麦克风权限。';permissionAction.textContent='再试一次'}finally{busy=false;permissionAction.disabled=false}}

  function refreshVoiceButtons(){voiceForward.textContent=forwardTemplate?'重录向前声':'录一个向前声';voiceBack.textContent=backTemplate?'重录返回声':'再设返回声（可选）';voiceBack.disabled=!forwardTemplate}
  function openVoiceSetup(){listening=false;cancelAnimationFrame(monitorRaf);monitorRaf=0;actionSheet.hidden=false;actionOptions.hidden=true;voiceSetup.hidden=false;refreshVoiceButtons();voiceHint.textContent=forwardTemplate?(backTemplate?'两个方向都已经记住；换文件也不用重录。':'向前声已经记住；换文件也会继续用。返回声不设也可以。'):'只做一次你以后想用的短声音。'}
  function beginCapture(dir){captureDirection=dir;actionSheet.hidden=true;voiceSetup.hidden=true;listening=true;setStatus(dir==='forward'?'现在做一次向前声':'现在做一次返回声',true,false);cooldownUntil=0;controlLoop()}
  function openActionSheet(){actionSheet.hidden=false;voiceSetup.hidden=true;actionOptions.hidden=false;actionOptions.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===controlMode);b.querySelector('em').textContent=b.dataset.mode===controlMode?'当前':'选择'})}
  async function closeReader(){cleanupControl();await releaseWake();try{renderTask?.cancel()}catch{}renderTask=null;pdfDoc=null;kind=null;pages=[];clearOwned();reader.hidden=true;home.hidden=false;pasteSheet.hidden=true;actionSheet.hidden=true;permission.hidden=true;filesInput.value='';setLoading(false);window.scrollTo({top:0,behavior:'instant'})}

  choose.onclick=()=>filesInput.click();filesInput.onchange=()=>{openFiles(filesInput.files);filesInput.value=''};
  pasteOpen.onclick=()=>{pasteSheet.hidden=false;pasteText.focus()};pasteClose.onclick=()=>pasteSheet.hidden=true;pasteModes.querySelectorAll('button').forEach(b=>b.onclick=()=>{pasteMode=b.dataset.mode;pasteModes.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});pasteUse.onclick=async()=>{const t=pasteText.value.trim();if(!t)return;pasteSheet.hidden=true;clearOwned();cleanupControl();await openText(t,pasteMode,'文字')};
  actionBtn.onclick=openActionSheet;actionClose.onclick=()=>actionSheet.hidden=true;actionOptions.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>prepareControl(b.dataset.mode,false));permissionAction.onclick=()=>activateMode(permission.dataset.mode||controlMode);
  voiceForward.onclick=()=>beginCapture('forward');voiceBack.onclick=()=>beginCapture('back');voiceDone.onclick=()=>{actionSheet.hidden=true;actionOptions.hidden=false;voiceSetup.hidden=true;controlMode='voice';localStorage.setItem('handsfree-control-v6','voice');listening=true;defaultStatus();controlLoop()};
  prevBtn.onclick=prevPage;nextBtn.onclick=nextPage;exit.onclick=closeReader;
  stage.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId}});stage.addEventListener('pointerup',e=>{if(!pointerStart||pointerStart.id!==e.pointerId)return;const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;pointerStart=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25){dx<0?nextPage():prevPage()}});
  document.addEventListener('keydown',e=>{if(reader.hidden)return;if(e.key==='ArrowRight'||e.key==='PageDown')nextPage();if(e.key==='ArrowLeft'||e.key==='PageUp')prevPage()});
  window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(reader.hidden)return;if(kind==='pdf')showPage(current)},150)});
  document.addEventListener('visibilitychange',async()=>{if(reader.hidden)return;if(document.hidden){listening=false;cancelAnimationFrame(monitorRaf);monitorRaf=0;await releaseWake()}else{await requestWake();if((audioStream||videoStream)&&!captureDirection){listening=true;cooldownUntil=performance.now()+500;controlLoop()}}});
  window.addEventListener('pagehide',()=>{cleanupControl();releaseWake();clearOwned()});
})();