(()=>{
'use strict';
const $=s=>document.querySelector(s);
const home=$('#home'),choose=$('#choose'),filesInput=$('#files'),pasteOpen=$('#pasteOpen'),error=$('#error');
const pasteSheet=$('#pasteSheet'),pasteClose=$('#pasteClose'),pasteText=$('#pasteText'),pasteUse=$('#pasteUse'),pasteModes=$('#pasteModes');
const reader=$('#reader'),exit=$('#exit'),stage=$('#stage'),pdfCanvas=$('#pdfCanvas'),imagePage=$('#imagePage'),textPage=$('#textPage'),textBody=$('#textBody'),stepNo=$('#stepNo'),measureText=$('#measureText'),loading=$('#loading'),loadingNote=$('#loadingNote'),pctx=pdfCanvas.getContext('2d',{alpha:false});
const faceVideo=$('#faceVideo'),fileKind=$('#fileKind'),pageNow=$('#pageNow'),pageTotal=$('#pageTotal'),statusDot=$('#statusDot'),statusText=$('#statusText'),actionBtn=$('#actionBtn'),prevBtn=$('#prev'),nextBtn=$('#next'),edgePrev=$('#edgePrev'),edgeNext=$('#edgeNext');
const mouthDock=$('#mouthDock'),mouthPeek=$('#mouthPeek'),mouthDockText=$('#mouthDockText'),mouthCtx=mouthPeek?.getContext('2d');
const actionSheet=$('#actionSheet'),actionClose=$('#actionClose'),actionOptions=$('#actionOptions'),commandSetup=$('#commandSetup'),forwardPhrase=$('#forwardPhrase'),backPhrase=$('#backPhrase'),changeForward=$('#changeForward'),changeBack=$('#changeBack'),resetCommands=$('#resetCommands');
const permission=$('#permission'),permissionTitle=$('#permissionTitle'),permissionHint=$('#permissionHint'),permissionAction=$('#permissionAction');
const capture=$('#listenCapture'),captureTitle=$('#captureTitle'),captureHint=$('#captureHint'),captureCancel=$('#captureCancel');
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;

let kind=null,pdfjs=null,pdfDoc=null,pdfWorker='',pages=[],current=1,total=1,renderToken=0,renderTask=null,ownedUrls=[];
let pasteMode='pages',controlMode=localStorage.getItem('handsfree-mode-v9')||localStorage.getItem('handsfree-mode-v7')||'command';
if(!['command','mouth'].includes(controlMode))controlMode='command';
let wake=null,pointerStart=null,resizeTimer=0,busy=false;
let commandWanted=false,commandRec=null,commandTimer=0,commandGeneration=0,lastCommandAt=0,commandStarting=false;
let captureRec=null,captureDirection=null,captureRetryTimer=0;
const DEFAULT_FORWARD={label:'下一页',forms:['下一页','下页','下一頁']};
const DEFAULT_BACK={label:'上一页',forms:['上一页','上页','上一頁']};
function readCommand(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');if(v&&v.label&&Array.isArray(v.forms)&&v.forms.length)return v}catch{}return fallback}
let forwardCommand=readCommand('handsfree-forward-command-v9',readCommand('handsfree-forward-command-v7',DEFAULT_FORWARD));
let backCommand=readCommand('handsfree-back-command-v9',readCommand('handsfree-back-command-v7',DEFAULT_BACK));
function saveCommand(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch{}}
let videoStream=null,faceLandmarker=null,faceLoop=0,faceLast=0,faceSeenUntil=0;
let neutralSamples=[],neutral=null,smoothBlend={},smoothPose=null,armed=false,neutralSince=0,candidate=null,candidateSince=0,cooldownUntil=0;
let headState=null,faceScale=.12;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
const mad=(a,m=median(a))=>median(a.map(v=>Math.abs(v-m)));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setError(t=''){error.hidden=!t;error.textContent=t}
function setLoading(on,note='请稍候'){loading.hidden=!on;loadingNote.textContent=note}
function own(url){ownedUrls.push(url);return url}
function clearOwned(){for(const u of ownedUrls)URL.revokeObjectURL(u);ownedUrls=[]}
function setStatus(text,live=false,hit=false){statusText.textContent=text;statusDot.classList.toggle('live',live);statusDot.classList.toggle('hit',hit)}
function defaultStatus(){setStatus(controlMode==='command'?`口令 · ${forwardCommand.label} / ${backCommand.label}`:'嘟嘴 / 点头向前 · 张嘴 / 摇头返回',controlMode==='command'?commandWanted:!!videoStream,false)}
async function requestWake(){if(document.hidden||wake||!navigator.wakeLock?.request)return;try{wake=await navigator.wakeLock.request('screen');wake.addEventListener?.('release',()=>wake=null,{once:true})}catch{}}
async function releaseWake(){const w=wake;wake=null;if(w)try{await w.release()}catch{}}
async function loadPdfLibrary(){if(pdfjs)return pdfjs;const sources=[{main:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.mjs',worker:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.worker.mjs'},{main:'https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.mjs',worker:'https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.worker.mjs'}];let last=null;for(const s of sources){try{pdfjs=await import(s.main);pdfWorker=s.worker;break}catch(e){last=e}}if(!pdfjs)throw last||new Error('pdfjs');pdfjs.GlobalWorkerOptions.workerSrc=pdfWorker;return pdfjs}
async function loadZip(){const urls=['https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm','https://esm.sh/jszip@3.10.1'];let last=null;for(const u of urls){try{const m=await import(u);return m.default||m}catch(e){last=e}}throw last||new Error('zip')}
function resolvePath(base,rel){if(/^([a-z]+:|\/)/i.test(rel))return rel;const parts=base.split('/').slice(0,-1).concat(rel.split('/')),out=[];for(const p of parts){if(!p||p==='.')continue;if(p==='..')out.pop();else out.push(p)}return out.join('/')}
function markdownBlocks(text){const lines=String(text).replace(/\r/g,'').split('\n'),blocks=[];let para=[],list=null;const inline=s=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');const flush=()=>{if(para.length){blocks.push(`<p>${inline(para.join(' '))}</p>`);para=[]}};const closeList=()=>{if(list){blocks.push(`<${list.tag}>${list.items.map(x=>`<li>${inline(x)}</li>`).join('')}</${list.tag}>`);list=null}};for(const raw of lines){const line=raw.trim();if(!line){flush();closeList();continue}let m=line.match(/^(#{1,3})\s+(.+)$/);if(m){flush();closeList();const n=m[1].length;blocks.push(`<h${n}>${inline(m[2])}</h${n}>`);continue}m=line.match(/^>\s*(.+)$/);if(m){flush();closeList();blocks.push(`<blockquote>${inline(m[1])}</blockquote>`);continue}m=line.match(/^[-*•]\s+(.+)$/);if(m){flush();if(!list||list.tag!=='ul'){closeList();list={tag:'ul',items:[]}}list.items.push(m[1]);continue}m=line.match(/^\d+[.)、]\s*(.+)$/);if(m){flush();if(!list||list.tag!=='ol'){closeList();list={tag:'ol',items:[]}}list.items.push(m[1]);continue}para.push(line)}flush();closeList();return blocks}
function stepBlocks(text){const lines=String(text).replace(/\r/g,'').split('\n'),steps=[];let cur=[];const push=()=>{const s=cur.join('\n').trim();if(s)steps.push(s);cur=[]};for(const raw of lines){const line=raw.trim();if(!line){if(cur.length)push();continue}if(/^(?:\d+[.)、]|[-*•]|第\s*\d+\s*步)/.test(line)){if(cur.length)push();cur=[line.replace(/^(?:\d+[.)、]|[-*•])\s*/,'')]}else cur.push(line)}push();if(steps.length<2)return String(text).split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean);return steps}
function setMeasureWidth(){const r=stage.getBoundingClientRect();measureText.style.width=`${Math.max(240,Math.min(740,r.width-40))}px`;measureText.style.maxHeight=`${Math.max(260,r.height-40)}px`}
function paginateBlocks(blocks){setMeasureWidth();const maxH=Math.max(220,stage.getBoundingClientRect().height-72),made=[];let cur=[];for(const b of blocks){cur.push(b);measureText.innerHTML=cur.join('');if(measureText.scrollHeight>maxH&&cur.length>1){cur.pop();made.push(cur.join(''));cur=[b]}}if(cur.length)made.push(cur.join(''));return made.length?made:['<p>没有可显示的文字。</p>']}
async function openText(text,mode='pages',label='文字'){reader.hidden=false;home.hidden=true;kind=mode==='steps'?'steps':'text';fileKind.textContent=mode==='steps'?'下一步':label;pages=mode==='steps'?stepBlocks(text).map((s,i)=>({html:`<div>${markdownBlocks(s).join('')}</div>`,step:i+1})):paginateBlocks(markdownBlocks(text)).map(html=>({html}));total=pages.length;current=1;pageTotal.textContent=String(total);await showPage(1);await prepareControl(controlMode,true);requestWake()}
async function openEpub(file){setLoading(true,'正在读取 EPUB');const JSZip=await loadZip(),zip=await JSZip.loadAsync(await file.arrayBuffer());const container=await zip.file('META-INF/container.xml')?.async('text');if(!container)throw new Error('epub');const cx=new DOMParser().parseFromString(container,'application/xml'),root=cx.querySelector('rootfile')?.getAttribute('full-path');if(!root)throw new Error('epub');const opfText=await zip.file(root)?.async('text');if(!opfText)throw new Error('epub');const opf=new DOMParser().parseFromString(opfText,'application/xml'),items={};opf.querySelectorAll('item').forEach(i=>items[i.getAttribute('id')]={href:i.getAttribute('href'),type:i.getAttribute('media-type')});const blocks=[];for(const ir of opf.querySelectorAll('spine itemref')){const it=items[ir.getAttribute('idref')];if(!it?.href)continue;const path=resolvePath(root,it.href),x=await zip.file(path)?.async('text');if(!x)continue;const doc=new DOMParser().parseFromString(x,'text/html');doc.querySelectorAll('script,style,nav').forEach(n=>n.remove());const nodes=[...doc.body.querySelectorAll('h1,h2,h3,p,li,blockquote')];if(nodes.length){for(const n of nodes){const t=n.textContent.trim();if(!t)continue;const tag=/^H[123]$/.test(n.tagName)?n.tagName.toLowerCase():n.tagName==='LI'?'li':n.tagName==='BLOCKQUOTE'?'blockquote':'p';blocks.push(`<${tag}>${esc(t)}</${tag}>`)}}else{const t=doc.body.textContent.trim();if(t)blocks.push(`<p>${esc(t)}</p>`)}}reader.hidden=false;home.hidden=true;kind='text';fileKind.textContent='EPUB';pages=paginateBlocks(blocks).map(html=>({html}));total=pages.length;current=1;pageTotal.textContent=String(total);setLoading(false);await showPage(1);await prepareControl(controlMode,true);requestWake()}
function loadImage(url){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url})}
function toBlob(canvas,type='image/jpeg'){return new Promise((ok,no)=>canvas.toBlob(b=>b?ok(b):no(new Error('blob')),type,type==='image/jpeg'?.94:undefined))}
async function imagePages(files){const sorted=[...files].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})),out=[];for(const file of sorted){const url=own(URL.createObjectURL(file)),img=await loadImage(url),w=img.naturalWidth,h=img.naturalHeight;if(h>w*2.15&&window.LONG_CUTTER){const cuts=LONG_CUTTER.find(img,w,h,1.68),bounds=[0,...cuts,h];for(let i=0;i<bounds.length-1;i++){const y=Math.round(bounds[i]),hh=Math.max(1,Math.round(bounds[i+1])-y),c=document.createElement('canvas');c.width=w;c.height=hh;c.getContext('2d').drawImage(img,0,y,w,hh,0,0,w,hh);const b=await toBlob(c,file.type==='image/png'?'image/png':'image/jpeg');out.push({type:'image',url:own(URL.createObjectURL(b))})}}else out.push({type:'image',url})}return out}
async function openFiles(list){setError('');const fs=[...list];if(!fs.length)return;clearOwned();cleanupControl();try{const pdfs=fs.filter(f=>f.type==='application/pdf'||/\.pdf$/i.test(f.name)),epubs=fs.filter(f=>/\.epub$/i.test(f.name)),texts=fs.filter(f=>f.type.startsWith('text/')||/\.(txt|md|markdown)$/i.test(f.name)),imgs=fs.filter(f=>f.type.startsWith('image/'));if([pdfs.length>0,epubs.length>0,texts.length>0,imgs.length>0].filter(Boolean).length>1)throw new Error('mixed');reader.hidden=false;home.hidden=true;setLoading(true,'正在打开内容');if(pdfs.length){if(pdfs.length>1)throw new Error('onepdf');kind='pdf';fileKind.textContent='PDF';const lib=await loadPdfLibrary(),data=new Uint8Array(await pdfs[0].arrayBuffer());pdfDoc=await lib.getDocument({data}).promise;total=pdfDoc.numPages;pages=[]}else if(epubs.length){if(epubs.length>1)throw new Error('oneepub');await openEpub(epubs[0]);return}else if(texts.length){const text=(await Promise.all(texts.map(f=>f.text()))).join('\n\n');setLoading(false);await openText(text,'pages','文字');return}else if(imgs.length){kind='images';fileKind.textContent='图片';pages=await imagePages(imgs);total=pages.length}else throw new Error('unsupported');current=1;pageTotal.textContent=String(total);setLoading(false);await showPage(1);await prepareControl(controlMode,true);requestWake()}catch(e){console.error(e);await closeReader();setError(e?.message==='mixed'?'不同类型请分开打开。':e?.message==='onepdf'?'一次先打开一个 PDF。':e?.message==='oneepub'?'一次先打开一本 EPUB。':'这个内容没有成功打开。')}}
async function showPage(n,flashDir=null){if(!kind)return;current=clamp(n,1,total);pageNow.textContent=String(current);prevBtn.disabled=current<=1;nextBtn.disabled=current>=total;if(flashDir)flashEdge(flashDir);pdfCanvas.hidden=true;imagePage.hidden=true;textPage.hidden=true;stepNo.hidden=true;if(kind==='images'){imagePage.src=pages[current-1].url;imagePage.hidden=false;try{await imagePage.decode()}catch{}return}if(kind==='text'||kind==='steps'){textBody.innerHTML=pages[current-1].html;textPage.hidden=false;textPage.classList.toggle('step-page',kind==='steps');if(kind==='steps'){stepNo.hidden=false;stepNo.textContent=String(current).padStart(2,'0')}return}const token=++renderToken;try{renderTask?.cancel()}catch{}renderTask=null;const page=await pdfDoc.getPage(current);if(token!==renderToken)return;const base=page.getViewport({scale:1}),r=stage.getBoundingClientRect(),maxW=Math.max(120,r.width-8),maxH=Math.max(120,r.height-8),fit=Math.min(maxW/base.width,maxH/base.height),dpr=Math.min(2,window.devicePixelRatio||1),vp=page.getViewport({scale:fit*dpr});pdfCanvas.width=Math.max(1,Math.round(vp.width));pdfCanvas.height=Math.max(1,Math.round(vp.height));pdfCanvas.style.width=`${vp.width/dpr}px`;pdfCanvas.style.height=`${vp.height/dpr}px`;pctx.fillStyle='#fff';pctx.fillRect(0,0,pdfCanvas.width,pdfCanvas.height);pdfCanvas.hidden=false;renderTask=page.render({canvasContext:pctx,viewport:vp});try{await renderTask.promise}catch(e){if(e?.name!=='RenderingCancelledException')throw e}finally{if(token===renderToken)renderTask=null}}
function flashEdge(dir){const el=dir==='prev'?edgePrev:edgeNext;el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),220)}
function nextPage(){if(current<total)showPage(current+1,'next');else{flashEdge('next');setStatus('已经是最后一页',true,true);setTimeout(defaultStatus,650)}}
function prevPage(){if(current>1)showPage(current-1,'prev');else{flashEdge('prev');setStatus('已经是第一页',true,true);setTimeout(defaultStatus,650)}}
function cleanPhrase(s){return String(s||'').toLowerCase().normalize('NFKC').replace(/[頁]/g,'页').replace(/[後]/g,'后').replace(/[，。！？、,.!?；;：:\s“”‘’"'（）()\[\]【】]/g,'').trim()}
function lev(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_, i)=>i),cur=new Array(b.length+1);for(let i=1;i<=a.length;i++){cur[0]=i;for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));[prev,cur]=[cur,prev]}return prev[b.length]}
function formScore(text,form){const t=cleanPhrase(text),f=cleanPhrase(form);if(!t||!f)return 0;if(t===f)return 1;const max=Math.max(t.length,f.length),d=lev(t,f);if(Math.min(t.length,f.length)<=3)return 0;if(max<=7&&d===1&&Math.abs(t.length-f.length)<=1)return .90;const r=1-d/max;return r>=.88?r:0}
function commandScore(alts,cmd){let best=0;for(const a of alts)for(const f of cmd.forms||[cmd.label])best=Math.max(best,formScore(a,f));return best}
function handleRecognized(alts){const now=performance.now();if(now-lastCommandAt<500)return;const sf=commandScore(alts,forwardCommand),sb=commandScore(alts,backCommand);if(sf>=.88&&sf>sb+.06){lastCommandAt=now;nextPage();setStatus(`${forwardCommand.label} · 向前`,true,true);setTimeout(defaultStatus,600)}else if(sb>=.88&&sb>sf+.06){lastCommandAt=now;prevPage();setStatus(`${backCommand.label} · 返回`,true,true);setTimeout(defaultStatus,600)}else if(Math.max(sf,sb)>.68){setStatus('听到了，但不是已设口令',true,false);setTimeout(defaultStatus,620)}}
function recognitionLang(){const labels=`${forwardCommand.label} ${backCommand.label}`;if(/[\u3400-\u9fff]/.test(labels))return 'zh-CN';const nav=navigator.language||'en-US';return /^zh/i.test(nav)?'en-US':nav}
function newRecognizer(){if(!SpeechRecognition)return null;const r=new SpeechRecognition();r.lang=recognitionLang();r.continuous=false;r.interimResults=true;r.maxAlternatives=5;return r}
function stopCommand(){commandWanted=false;commandGeneration++;clearTimeout(commandTimer);commandTimer=0;commandStarting=false;if(commandRec){commandRec.onend=commandRec.onerror=commandRec.onresult=null;try{commandRec.abort()}catch{}commandRec=null}}
function scheduleCommand(delay=140){if(!commandWanted||document.hidden||controlMode!=='command')return;clearTimeout(commandTimer);const g=commandGeneration;commandTimer=setTimeout(()=>{if(g!==commandGeneration||!commandWanted)return;runCommandSession(g)},delay)}
function runCommandSession(g){if(!commandWanted||commandStarting||g!==commandGeneration||document.hidden)return;commandStarting=true;const r=newRecognizer();if(!r){commandStarting=false;showPermission('command','当前浏览器不支持口令识别。');return}commandRec=r;let heard=false,finished=false;const done=(delay=120)=>{if(finished)return;finished=true;commandStarting=false;if(commandRec===r)commandRec=null;if(commandWanted&&g===commandGeneration)scheduleCommand(delay)};r.onstart=()=>{commandStarting=false;permission.hidden=true;setStatus(`在听 · ${forwardCommand.label} / ${backCommand.label}`,true,false)};r.onresult=e=>{heard=true;for(let i=e.resultIndex;i<e.results.length;i++){const res=e.results[i],alts=[];for(let j=0;j<res.length;j++)alts.push(res[j].transcript);if(res.isFinal)handleRecognized(alts);else{const sf=commandScore(alts,forwardCommand),sb=commandScore(alts,backCommand);if(Math.max(sf,sb)>.82)setStatus(`听到 · ${alts[0]}`,true,false)}}};r.onerror=e=>{commandStarting=false;if(['not-allowed','service-not-allowed','audio-capture'].includes(e.error)){commandWanted=false;permission.hidden=false;permissionTitle.textContent='需要麦克风';permissionHint.textContent='允许语音识别后才能使用口令。';permissionAction.textContent='开启';return}if(e.error==='no-speech')done(80);else done(220)};r.onend=()=>done(heard?90:130);try{r.start()}catch{done(260)}}
function startCommand(){if(!SpeechRecognition)throw new Error('nospeech');cleanupVideo();stopCommand();controlMode='command';localStorage.setItem('handsfree-mode-v9','command');commandWanted=true;commandGeneration++;permission.hidden=true;scheduleCommand(40);syncModeUI();defaultStatus()}
function refreshCommandUI(){forwardPhrase.textContent=forwardCommand.label;backPhrase.textContent=backCommand.label}
function stopCapture(){clearTimeout(captureRetryTimer);captureRetryTimer=0;if(captureRec){captureRec.onend=captureRec.onerror=captureRec.onresult=null;try{captureRec.abort()}catch{}captureRec=null}captureDirection=null;capture.hidden=true}
function captureCommand(dir){if(!SpeechRecognition){setStatus('当前浏览器不支持口令识别',false,false);return}stopCommand();stopCapture();captureDirection=dir;capture.hidden=false;captureTitle.textContent=dir==='forward'?'说一次向前口令':'说一次返回口令';captureHint.textContent='正常说一次即可。听到后会直接记住，不用重复。';setStatus('正在等你的口令',true,false);setTimeout(()=>runCapture(dir),260)}
function runCapture(dir){if(captureDirection!==dir)return;const r=newRecognizer();if(!r){captureHint.textContent='当前浏览器无法开始语音识别。';return}captureRec=r;let best='',forms=[],done=false;const finishSuccess=()=>{if(done||!best)return;done=true;const cmd={label:best.trim(),forms:forms.length?forms:[cleanPhrase(best)]};if(dir==='forward'){forwardCommand=cmd;saveCommand('handsfree-forward-command-v9',cmd)}else{backCommand=cmd;saveCommand('handsfree-back-command-v9',cmd)}refreshCommandUI();navigator.vibrate?.(12);captureHint.textContent=`记住了：${best}`;setTimeout(()=>{stopCapture();openCommandSetup();if(controlMode==='command')startCommand()},420)};r.onstart=()=>{captureHint.textContent='正在听，直接说。'};r.onresult=e=>{const res=e.results[e.resultIndex]||e.results[0];if(!res)return;forms=[];for(let j=0;j<res.length;j++){const raw=res[j].transcript?.trim(),c=cleanPhrase(raw);if(raw&&c&&!forms.includes(c)){forms.push(c);if(!best)best=raw}}if(best)captureHint.textContent=`听到：${best}`;if(res.isFinal)finishSuccess()};r.onerror=e=>{if(done)return;if(['not-allowed','service-not-allowed','audio-capture'].includes(e.error)){captureHint.textContent='麦克风没有开启。';return}captureHint.textContent='这次没听清，我再听一次。';captureRetryTimer=setTimeout(()=>runCapture(dir),420)};r.onend=()=>{if(done)return;if(best)finishSuccess();else{captureHint.textContent='还没听到，再说一次。';captureRetryTimer=setTimeout(()=>runCapture(dir),320)}};try{r.start()}catch{captureHint.textContent='正在重新打开麦克风…';captureRetryTimer=setTimeout(()=>runCapture(dir),520)}}
function blendMap(result){const cats=result?.faceBlendshapes?.[0]?.categories||[],m={};for(const c of cats){const k=String(c.categoryName||c.displayName||'').replace(/[_\s-]/g,'').toLowerCase();m[k]=Number(c.score)||0}return{pucker:m.mouthpucker||0,funnel:m.mouthfunnel||0,jaw:m.jawopen||0,smile:Math.max(m.mouthsmileleft||0,m.mouthsmileright||0),stretch:Math.max(m.mouthstretchleft||0,m.mouthstretchright||0),press:Math.max(m.mouthpressleft||0,m.mouthpressright||0),close:m.mouthclose||0}}
function facePose(lm){const l=lm?.[234],r=lm?.[454],t=lm?.[10],c=lm?.[152],n=lm?.[1];if(!l||!r||!t||!c||!n)return null;const w=Math.hypot(r.x-l.x,r.y-l.y),h=Math.hypot(c.x-t.x,c.y-t.y);if(w<.035||h<.05)return null;faceScale=Math.min(w,h);return{yaw:(n.x-(l.x+r.x)/2)/w,pitch:(n.y-(t.y+c.y)/2)/h,scale:faceScale}}
function mouthScores(v){const p=Math.max(v.pucker,v.funnel*.96),other=Math.max(v.smile,v.stretch),pScore=p-v.jaw*.22-other*.15;const oScore=v.jaw-p*.23-v.close*.10;return{pScore,oScore,p,jaw:v.jaw}}
function smoothObj(prev,next,a=.38){if(!prev)return{...next};const out={...prev};for(const k of Object.keys(next))out[k]=(prev[k]??next[k])*(1-a)+next[k]*a;return out}
function renderMouthOutline(lm){if(!mouthCtx||!lm?.length)return;const outer=[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78,61].map(i=>lm[i]).filter(Boolean),inner=[78,191,80,81,82,13,312,311,310,415,308,324,318,402,317,14,87,178,88,95,78].map(i=>lm[i]).filter(Boolean),all=[...outer,...inner];if(!all.length)return;let minX=1,maxX=0,minY=1,maxY=0;for(const p of all){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const px=(maxX-minX)*.16+.004,py=(maxY-minY)*.3+.004,w=mouthPeek.width,h=mouthPeek.height,minx=minX-px,maxx=maxX+px,miny=minY-py,maxy=maxY+py;mouthCtx.clearRect(0,0,w,h);mouthCtx.lineWidth=1.2;mouthCtx.lineCap='round';mouthCtx.lineJoin='round';const draw=(pts,alpha)=>{mouthCtx.strokeStyle=`rgba(255,255,255,${alpha})`;mouthCtx.beginPath();pts.forEach((p,i)=>{const x=(p.x-minx)/(maxx-minx)*w,y=(p.y-miny)/(maxy-miny)*h;i?mouthCtx.lineTo(x,y):mouthCtx.moveTo(x,y)});mouthCtx.stroke()};draw(outer,.72);draw(inner,.33)}
async function loadFace(){if(faceLandmarker)return faceLandmarker;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,L=mod.FaceLandmarker||mod.default?.FaceLandmarker;if(!F||!L)throw 0;const vision=await F.forVisionTasks(s.wasm);faceLandmarker=await L.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true,outputFacialTransformationMatrixes:true,minFaceDetectionConfidence:.16,minFacePresenceConfidence:.16,minTrackingConfidence:.16});return faceLandmarker}catch(e){last=e;faceLandmarker=null}}throw last||new Error('face')}
function resetGesture(){neutralSamples=[];neutral=null;smoothBlend={};smoothPose=null;armed=false;neutralSince=0;candidate=null;candidateSince=0;cooldownUntil=0;headState=null}
function buildNeutral(){if(neutralSamples.length<10)return false;const p=neutralSamples.map(x=>x.m.pScore),o=neutralSamples.map(x=>x.m.oScore),y=neutralSamples.map(x=>x.pose.yaw),pi=neutralSamples.map(x=>x.pose.pitch);neutral={p:median(p),o:median(o),yaw:median(y),pitch:median(pi),pNoise:mad(p),oNoise:mad(o),yNoise:mad(y),piNoise:mad(pi)};mouthDockText.textContent='动作已锁';return true}
function gestureHit(dir,label){cooldownUntil=performance.now()+580;armed=false;neutralSince=0;candidate=null;headState=null;mouthDock.classList.add('hit');setTimeout(()=>mouthDock.classList.remove('hit'),220);dir==='next'?nextPage():prevPage();setStatus(label,true,true);setTimeout(defaultStatus,580)}
function evaluateGesture(now,blend,pose){if(!neutral)return;const m=mouthScores(blend),dy=pose.yaw-neutral.yaw,dp=pose.pitch-neutral.pitch;const pT=neutral.p+Math.max(.055,neutral.pNoise*4.2),oT=neutral.o+Math.max(.095,neutral.oNoise*4.2),yT=Math.max(.032,neutral.yNoise*5.0),piT=Math.max(.022,neutral.piNoise*5.0);const mouthNeutral=m.pScore<neutral.p+Math.max(.035,(pT-neutral.p)*.52)&&m.oScore<neutral.o+Math.max(.055,(oT-neutral.o)*.48);const headNeutral=Math.abs(dy)<yT*.45&&Math.abs(dp)<piT*.48;const neutralNow=mouthNeutral&&headNeutral;if(neutralNow){if(!neutralSince)neutralSince=now;if(now-neutralSince>170)armed=true}else neutralSince=0;if(now<cooldownUntil||!armed)return;let mouthType=null;if(m.pScore>pT&&m.jaw<Math.max(.34,neutral.o+.20)&&m.oScore<oT*.82)mouthType='pucker';else if(m.oScore>oT&&m.p<Math.max(.42,neutral.p+.24))mouthType='open';if(mouthType){if(candidate?.type!==mouthType){candidate={type:mouthType};candidateSince=now}else if(now-candidateSince>105){gestureHit(mouthType==='pucker'?'next':'prev',mouthType==='pucker'?'嘟嘴 · 向前':'张嘴 · 返回');return}}else if(candidate?.type==='pucker'||candidate?.type==='open')candidate=null;if(!headState){if(Math.abs(dp)>piT&&Math.abs(dy)<yT*1.25)headState={type:'nod',start:now,peak:Math.abs(dp)};else if(Math.abs(dy)>yT&&Math.abs(dp)<piT*1.6)headState={type:'shake',start:now,side:Math.sign(dy)||1,cross:false}}else if(headState.type==='nod'){headState.peak=Math.max(headState.peak,Math.abs(dp));if(now-headState.start>900)headState=null;else if(Math.abs(dp)<piT*.45&&now-headState.start>90&&headState.peak>piT*1.02){gestureHit('next','点头 · 向前');return}}else if(headState.type==='shake'){if(now-headState.start>1150)headState=null;else if(!headState.cross&&Math.sign(dy)===-headState.side&&Math.abs(dy)>yT*.82)headState.cross=true;else if(headState.cross&&Math.abs(dy)<yT*.5){gestureHit('prev','摇头 · 返回');return}}}
function startFaceLoop(){cancelAnimationFrame(faceLoop);faceLast=0;const loop=now=>{faceLoop=requestAnimationFrame(loop);if(!videoStream||!faceLandmarker||faceVideo.readyState<2||document.hidden||now-faceLast<74)return;faceLast=now;try{const r=faceLandmarker.detectForVideo(faceVideo,now),lm=r?.faceLandmarks?.[0],p=facePose(lm);if(!lm||!p||!r?.faceBlendshapes?.length){if(now>faceSeenUntil){mouthDock.classList.remove('found');mouthDockText.textContent='脸不在范围';armed=false;neutralSince=0}return}faceSeenUntil=now+520;mouthDock.classList.add('found');mouthDockText.textContent=faceScale<.075?'已看到 · 稍远':'动作已锁';renderMouthOutline(lm);const b=blendMap(r);smoothBlend=smoothObj(Object.keys(smoothBlend).length?smoothBlend:null,b,.44);smoothPose=smoothObj(smoothPose,p,.34);const ms=mouthScores(smoothBlend);if(!neutral){neutralSamples.push({m:ms,pose:smoothPose});if(neutralSamples.length>=16)buildNeutral();return}evaluateGesture(now,smoothBlend,smoothPose)}catch{}};faceLoop=requestAnimationFrame(loop)}
async function setupMouth(){stopCommand();stopCapture();cleanupVideo();controlMode='mouth';localStorage.setItem('handsfree-mode-v9','mouth');videoStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});faceVideo.srcObject=videoStream;await faceVideo.play();await loadFace();mouthDock.hidden=false;mouthDockText.textContent='保持自然';resetGesture();startFaceLoop();const t0=performance.now();while(!neutral&&performance.now()-t0<1800)await sleep(50);if(!neutral)throw new Error('noface');permission.hidden=true;syncModeUI();defaultStatus()}
function cleanupVideo(){cancelAnimationFrame(faceLoop);faceLoop=0;if(videoStream){videoStream.getTracks().forEach(t=>t.stop());videoStream=null}faceVideo.srcObject=null;mouthDock.hidden=true;mouthDock.classList.remove('found','hit');mouthDockText.textContent='找动作';mouthCtx?.clearRect(0,0,mouthPeek.width,mouthPeek.height);resetGesture()}
function cleanupControl(){stopCommand();stopCapture();cleanupVideo();setStatus('免手操作未开启',false,false)}
function syncModeUI(){actionOptions.querySelectorAll('[data-mode]').forEach(b=>{const on=b.dataset.mode===controlMode;b.classList.toggle('active',on);const e=b.querySelector('em');if(e)e.textContent=on?'当前':'选择'})}
function showPermission(mode,msg=''){permission.hidden=false;permission.dataset.mode=mode;permissionTitle.textContent=mode==='command'?'开启口令':'开启无声动作';permissionHint.textContent=msg||(mode==='command'?`直接说“${forwardCommand.label} / ${backCommand.label}”。也可以各说一次自己的口令。`:'只开前置相机。正常阅读距离即可，嘟嘴 / 点头向前，张嘴 / 摇头返回。');permissionAction.textContent='开启'}
async function prepareControl(mode,auto=false){controlMode=mode;localStorage.setItem('handsfree-mode-v9',mode);cleanupControl();actionSheet.hidden=true;permission.hidden=true;syncModeUI();if(mode==='command'){if(!SpeechRecognition){showPermission(mode,'当前浏览器不支持口令识别，可以改用无声动作。');return}if(auto){try{startCommand();return}catch{}}showPermission(mode)}else{if(auto){try{await setupMouth();return}catch{cleanupVideo()}}showPermission(mode)}}
async function activateMode(mode){if(busy)return;busy=true;permissionAction.disabled=true;try{cleanupControl();controlMode=mode;localStorage.setItem('handsfree-mode-v9',mode);if(mode==='command')startCommand();else await setupMouth();permission.hidden=true;syncModeUI()}catch(e){console.error(e);cleanupControl();showPermission(mode,mode==='command'?'没有成功开启语音识别，请再试一次。':'需要前置相机权限，而且脸需要在镜头范围内。')}finally{busy=false;permissionAction.disabled=false}}
function openActionSheet(){refreshCommandUI();syncModeUI();actionSheet.hidden=false;commandSetup.hidden=true;actionOptions.hidden=false}
function openCommandSetup(){refreshCommandUI();syncModeUI();actionSheet.hidden=false;actionOptions.hidden=true;commandSetup.hidden=false}
async function closeReader(){cleanupControl();await releaseWake();try{renderTask?.cancel()}catch{}renderTask=null;pdfDoc=null;kind=null;pages=[];clearOwned();reader.hidden=true;home.hidden=false;pasteSheet.hidden=true;actionSheet.hidden=true;permission.hidden=true;filesInput.value='';setLoading(false);window.scrollTo({top:0,behavior:'instant'})}
choose.onclick=()=>filesInput.click();filesInput.onchange=()=>{openFiles(filesInput.files);filesInput.value=''};pasteOpen.onclick=()=>{pasteSheet.hidden=false;pasteText.focus()};pasteClose.onclick=()=>pasteSheet.hidden=true;pasteModes.querySelectorAll('button').forEach(b=>b.onclick=()=>{pasteMode=b.dataset.mode;pasteModes.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});pasteUse.onclick=async()=>{const t=pasteText.value.trim();if(!t)return;pasteSheet.hidden=true;clearOwned();cleanupControl();await openText(t,pasteMode,'文字')};actionBtn.onclick=openActionSheet;actionClose.onclick=()=>actionSheet.hidden=true;actionOptions.querySelectorAll('[data-mode]').forEach(b=>b.onclick=async()=>{const m=b.dataset.mode;controlMode=m;localStorage.setItem('handsfree-mode-v9',m);syncModeUI();if(m==='command'){cleanupControl();startCommand();openCommandSetup()}else{actionSheet.hidden=true;await prepareControl('mouth',false)}});changeForward.onclick=()=>captureCommand('forward');changeBack.onclick=()=>captureCommand('back');resetCommands.onclick=()=>{forwardCommand=DEFAULT_FORWARD;backCommand=DEFAULT_BACK;saveCommand('handsfree-forward-command-v9',forwardCommand);saveCommand('handsfree-back-command-v9',backCommand);refreshCommandUI();if(controlMode==='command')startCommand()};permissionAction.onclick=()=>activateMode(permission.dataset.mode||controlMode);captureCancel.onclick=()=>{stopCapture();openCommandSetup();if(controlMode==='command')startCommand()};prevBtn.onclick=prevPage;nextBtn.onclick=nextPage;exit.onclick=closeReader;stage.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId}});stage.addEventListener('pointerup',e=>{if(!pointerStart||pointerStart.id!==e.pointerId)return;const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;pointerStart=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25){dx<0?nextPage():prevPage()}});document.addEventListener('keydown',e=>{if(reader.hidden)return;if(e.key==='ArrowRight'||e.key==='PageDown')nextPage();if(e.key==='ArrowLeft'||e.key==='PageUp')prevPage()});window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(reader.hidden)return;if(kind==='pdf')showPage(current)},150)});document.addEventListener('visibilitychange',async()=>{if(reader.hidden)return;if(document.hidden){stopCommand();cancelAnimationFrame(faceLoop);faceLoop=0;await releaseWake()}else{await requestWake();if(controlMode==='command'){try{startCommand()}catch{showPermission('command')}}else if(videoStream)startFaceLoop()}});window.addEventListener('pagehide',()=>{cleanupControl();releaseWake();clearOwned()});refreshCommandUI();syncModeUI();
})();