(()=>{
'use strict';
const $=s=>document.querySelector(s);
const intro=$('#intro'),take=$('#take'),choose=$('#choose'),cameraInput=$('#cameraInput'),photoInput=$('#photoInput'),error=$('#error'),busy=$('#busy'),busyText=$('#busyText'),result=$('#result'),back=$('#back'),again=$('#again'),yesCount=$('#yesCount'),noCount=$('#noCount'),holdCount=$('#holdCount'),verdict=$('#verdict'),canvas=$('#canvas'),ctx=canvas.getContext('2d'),recognized=$('#recognized'),unknown=$('#unknown'),share=$('#share');
let recognizer=null,lastFileName='现场表决.png';
const MAP={Thumb_Up:{key:'yes',label:'赞成',color:'#246f5b'},Thumb_Down:{key:'no',label:'反对',color:'#d64f38'},Open_Palm:{key:'hold',label:'保留',color:'#315be8'}};
function setError(t=''){error.hidden=!t;error.textContent=t}
function setBusy(on,t='正在数'){busy.hidden=!on;busyText.textContent=t}
function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'))};img.src=url})}
async function loadRecognizer(){if(recognizer)return recognizer;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,G=mod.GestureRecognizer||mod.default?.GestureRecognizer;if(!F||!G)throw new Error('module');const vision=await F.forVisionTasks(s.wasm);for(const delegate of ['GPU','CPU']){try{recognizer=await G.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/gesture_recognizer/gesture_recognizer/float16/1/gesture_recognizer.task',delegate},runningMode:'IMAGE',numHands:20,minHandDetectionConfidence:.28,minHandPresenceConfidence:.28,minTrackingConfidence:.28});return recognizer}catch(e){last=e;recognizer=null}}}catch(e){last=e}}throw last||new Error('gesture')}
function setupCanvas(img){const max=1500,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));canvas.width=Math.max(2,Math.round(img.naturalWidth*scale));canvas.height=Math.max(2,Math.round(img.naturalHeight*scale));ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height)}
function boxFor(lm){let minX=1,minY=1,maxX=0,maxY=0;for(const p of lm||[]){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}if(maxX<=minX||maxY<=minY)return null;const px=(maxX-minX)*.14,py=(maxY-minY)*.14;return{x:clamp(minX-px,0,1)*canvas.width,y:clamp(minY-py,0,1)*canvas.height,w:clamp(maxX-minX+px*2,0,1)*canvas.width,h:clamp(maxY-minY+py*2,0,1)*canvas.height}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function drawMark(box,meta,index){if(!box)return;const lw=Math.max(2,Math.min(6,canvas.width/300));ctx.save();ctx.strokeStyle=meta.color;ctx.lineWidth=lw;ctx.strokeRect(box.x,box.y,box.w,box.h);const label=`${meta.label} ${index}`;ctx.font=`${Math.max(14,Math.round(canvas.width/48))}px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif`;const pad=Math.max(5,canvas.width/220),tw=ctx.measureText(label).width+pad*2,th=Math.max(24,canvas.width/34);let x=box.x,y=Math.max(0,box.y-th);if(x+tw>canvas.width)x=canvas.width-tw;ctx.fillStyle=meta.color;ctx.fillRect(x,y,tw,th);ctx.fillStyle='#fff';ctx.textBaseline='middle';ctx.fillText(label,x+pad,y+th/2);ctx.restore()}
function topGesture(group){const cats=group||[];let best=null;for(const c of cats){const name=c.categoryName||c.displayName||'',score=Number(c.score)||0;if(!best||score>best.score)best={name,score}}return best}
function renderCounts(counts,totalDetected,unknownCount){yesCount.textContent=String(counts.yes);noCount.textContent=String(counts.no);holdCount.textContent=String(counts.hold);const known=counts.yes+counts.no+counts.hold;recognized.textContent=`${known} 票`;unknown.textContent=`${unknownCount} 只手`;if(!known){verdict.textContent=totalDetected?'看到了手，但这次没有明确认成 👍 / 👎 / ✋。':'这张照片里没有找到可用的手。';return}if(counts.yes>counts.no)verdict.textContent=`赞成比反对多 ${counts.yes-counts.no} 票。${counts.hold?`另外 ${counts.hold} 票保留。`:''}`;else if(counts.no>counts.yes)verdict.textContent=`反对比赞成多 ${counts.no-counts.yes} 票。${counts.hold?`另外 ${counts.hold} 票保留。`:''}`;else verdict.textContent=`赞成和反对一样多${counts.hold?`，另有 ${counts.hold} 票保留`:''}。`}
async function analyze(file){if(!file||!file.type.startsWith('image/'))return;setError('');intro.hidden=true;result.hidden=true;setBusy(true,'正在打开照片');try{const [img,rec]=await Promise.all([loadImage(file),loadRecognizer()]);setupCanvas(img);setBusy(true,'正在找手势');const out=await Promise.resolve(rec.recognize(canvas));const gestures=out?.gestures||[],landmarks=out?.landmarks||[],counts={yes:0,no:0,hold:0};let unknownCount=0,markIndex=0;const totalDetected=Math.max(gestures.length,landmarks.length);for(let i=0;i<totalDetected;i++){const top=topGesture(gestures[i]),meta=top&&top.score>=.50?MAP[top.name]:null;if(meta){counts[meta.key]++;markIndex++;drawMark(boxFor(landmarks[i]),meta,markIndex)}else{unknownCount++;const b=boxFor(landmarks[i]);if(b){ctx.save();ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=Math.max(1.5,canvas.width/420);ctx.setLineDash([8,7]);ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.restore()}}}setBusy(false);result.hidden=false;renderCounts(counts,totalDetected,unknownCount);lastFileName=`现场表决-${counts.yes}-${counts.no}-${counts.hold}.png`;window.scrollTo({top:0,behavior:'instant'})}catch(e){console.error(e);setBusy(false);intro.hidden=false;setError(e?.message==='image'?'这张照片没有成功打开。':'手势识别组件没有准备好。换个网络后再试。')}}
function pickCamera(){cameraInput.click()}
take.onclick=pickCamera;choose.onclick=()=>photoInput.click();cameraInput.onchange=()=>{analyze(cameraInput.files?.[0]);cameraInput.value=''};photoInput.onchange=()=>{analyze(photoInput.files?.[0]);photoInput.value=''};again.onclick=pickCamera;back.onclick=()=>{result.hidden=true;busy.hidden=true;intro.hidden=false;setError('');window.scrollTo({top:0,behavior:'instant'})};share.onclick=async()=>{const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)return;const file=new File([blob],lastFileName,{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file]});return}}catch{}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=lastFileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)};
})();