(()=>{
'use strict';
const $=s=>document.querySelector(s);
const intro=$('#intro'),take=$('#take'),choose=$('#choose'),cameraInput=$('#cameraInput'),photoInput=$('#photoInput'),error=$('#error'),busy=$('#busy'),busyText=$('#busyText'),result=$('#result'),back=$('#back'),again=$('#again'),yesCount=$('#yesCount'),noCount=$('#noCount'),holdCount=$('#holdCount'),verdict=$('#verdict'),canvas=$('#canvas'),ctx=canvas.getContext('2d'),recognized=$('#recognized'),unknown=$('#unknown'),share=$('#share');
let recognizer=null,lastFileName='现场表决.png';
const META={yes:{label:'赞成',color:'#246f5b'},no:{label:'反对',color:'#d64f38'},hold:{label:'保留',color:'#315be8'}};
const NAME_TO_KEY={Thumb_Up:'yes',Thumb_Down:'no',Open_Palm:'hold'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
function setError(t=''){error.hidden=!t;error.textContent=t}
function setBusy(on,t='正在数'){busy.hidden=!on;busyText.textContent=t}
function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'))};img.src=url})}
async function loadRecognizer(){if(recognizer)return recognizer;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,G=mod.GestureRecognizer||mod.default?.GestureRecognizer;if(!F||!G)throw new Error('module');const vision=await F.forVisionTasks(s.wasm);for(const delegate of ['GPU','CPU']){try{recognizer=await G.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/gesture_recognizer/gesture_recognizer/float16/1/gesture_recognizer.task',delegate},runningMode:'IMAGE',numHands:20,minHandDetectionConfidence:.18,minHandPresenceConfidence:.18,minTrackingConfidence:.18});return recognizer}catch(e){last=e;recognizer=null}}}catch(e){last=e}}throw last||new Error('gesture')}
function makeSource(img){const max=2400,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(2,Math.round(img.naturalWidth*scale));c.height=Math.max(2,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c}
function buildTiles(w,h){const tiles=[{x:0,y:0,w,h,name:'整张'}];const fw=.62,fh=.62,tw=w*fw,th=h*fh;for(const yy of [0,h-th])for(const xx of [0,w-tw])tiles.push({x:Math.round(xx),y:Math.round(yy),w:Math.round(tw),h:Math.round(th),name:'局部'});return tiles}
function workFor(src,tile){const max=1120,scale=Math.min(1,max/Math.max(tile.w,tile.h)),c=document.createElement('canvas');c.width=Math.max(2,Math.round(tile.w*scale));c.height=Math.max(2,Math.round(tile.h*scale));c.getContext('2d').drawImage(src,tile.x,tile.y,tile.w,tile.h,0,0,c.width,c.height);return c}
function mapLandmarks(lm,tile,fullW,fullH){return(lm||[]).map(p=>({x:(tile.x+p.x*tile.w)/fullW,y:(tile.y+p.y*tile.h)/fullH,z:p.z||0}))}
function boxNorm(lm){let minX=1,minY=1,maxX=0,maxY=0;for(const p of lm||[]){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}if(maxX<=minX||maxY<=minY)return null;return{x:minX,y:minY,w:maxX-minX,h:maxY-minY,cx:(minX+maxX)/2,cy:(minY+maxY)/2}}
function iou(a,b){const x1=Math.max(a.x,b.x),y1=Math.max(a.y,b.y),x2=Math.min(a.x+a.w,b.x+b.w),y2=Math.min(a.y+a.h,b.y+b.h),iw=Math.max(0,x2-x1),ih=Math.max(0,y2-y1),inter=iw*ih,uni=a.w*a.h+b.w*b.h-inter;return uni?inter/uni:0}
function sameHand(a,b){const d=Math.hypot(a.box.cx-b.box.cx,a.box.cy-b.box.cy),s=Math.max(Math.hypot(a.box.w,a.box.h),Math.hypot(b.box.w,b.box.h));return iou(a.box,b.box)>.22||d<s*.30}
function topTargets(cats=[]){const out={yes:0,no:0,hold:0};for(const c of cats){const k=NAME_TO_KEY[c.categoryName||c.displayName||''];if(k)out[k]=Math.max(out[k],Number(c.score)||0)}return out}
function fingerExtended(lm,tip,pip,mcp){const w=lm[0];if(!w||!lm[tip]||!lm[pip]||!lm[mcp])return false;return dist(lm[tip],w)>dist(lm[pip],w)*1.07&&dist(lm[tip],lm[mcp])>dist(lm[pip],lm[mcp])*1.36}
function geometry(lm){if(!lm?.[20])return null;const b=boxNorm(lm);if(!b)return null;const ext=[fingerExtended(lm,8,6,5),fingerExtended(lm,12,10,9),fingerExtended(lm,16,14,13),fingerExtended(lm,20,18,17)],n=ext.filter(Boolean).length;const thumbLong=dist(lm[4],lm[2])>dist(lm[3],lm[2])*1.34;const thumbY=(lm[0].y-lm[4].y)/Math.max(.001,b.h);const spread=dist(lm[8],lm[20])/Math.max(.001,b.w);if(n>=3&&spread>.48)return{key:'hold',strength:clamp(.52+n*.09+Math.min(.12,(spread-.48)*.4),0,1)};if(n<=1&&thumbLong&&thumbY>.42)return{key:'yes',strength:clamp(.62+(thumbY-.42)*.42,0,1)};if(n<=1&&thumbLong&&thumbY<-.24)return{key:'no',strength:clamp(.60+(-thumbY-.24)*.45,0,1)};return null}
function classify(cats,lm){const model=topTargets(cats),entries=Object.entries(model).sort((a,b)=>b[1]-a[1]),[bestKey,bestScore]=entries[0],geo=geometry(lm);if(bestScore>=.58)return{key:bestKey,conf:bestScore};if(geo&&geo.key===bestKey&&bestScore>=.30)return{key:bestKey,conf:clamp(bestScore*.58+geo.strength*.52,0,1)};if(geo&&geo.strength>=.76&&bestScore<.44)return{key:geo.key,conf:geo.strength*.72};return null}
function addDetection(all,d){const hit=all.find(x=>sameHand(x,d));if(!hit){all.push(d);return}hit.views++;if(d.box.w*d.box.h>hit.box.w*hit.box.h){hit.box=d.box;hit.landmarks=d.landmarks}for(const k of ['yes','no','hold'])hit.votes[k]+=d.votes[k]||0;hit.maxConf=Math.max(hit.maxConf,d.maxConf)}
function finalizeDetection(d){const entries=Object.entries(d.votes).sort((a,b)=>b[1]-a[1]),[key,score]=entries[0],second=entries[1][1];if(score>=.56&&(score>=second*1.14||score-second>.18))return{...d,key,conf:score};return{...d,key:null,conf:score}}
function drawMark(box,meta,index){if(!box)return;const x=box.x*canvas.width,y=box.y*canvas.height,w=box.w*canvas.width,h=box.h*canvas.height,lw=Math.max(2,Math.min(6,canvas.width/300));ctx.save();ctx.strokeStyle=meta.color;ctx.lineWidth=lw;ctx.strokeRect(x,y,w,h);const label=`${meta.label} ${index}`;ctx.font=`${Math.max(14,Math.round(canvas.width/48))}px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif`;const pad=Math.max(5,canvas.width/220),tw=ctx.measureText(label).width+pad*2,th=Math.max(24,canvas.width/34);let lx=x,ly=Math.max(0,y-th);if(lx+tw>canvas.width)lx=canvas.width-tw;ctx.fillStyle=meta.color;ctx.fillRect(lx,ly,tw,th);ctx.fillStyle='#fff';ctx.textBaseline='middle';ctx.fillText(label,lx+pad,ly+th/2);ctx.restore()}
function drawUnknown(box){if(!box)return;ctx.save();ctx.strokeStyle='rgba(255,255,255,.82)';ctx.lineWidth=Math.max(1.5,canvas.width/420);ctx.setLineDash([8,7]);ctx.strokeRect(box.x*canvas.width,box.y*canvas.height,box.w*canvas.width,box.h*canvas.height);ctx.restore()}
function renderCounts(counts,totalDetected,unknownCount){yesCount.textContent=String(counts.yes);noCount.textContent=String(counts.no);holdCount.textContent=String(counts.hold);const known=counts.yes+counts.no+counts.hold;recognized.textContent=`${known} 票`;unknown.textContent=`${unknownCount} 只手`;if(!known){verdict.textContent=totalDetected?'看到了手，但这次没有明确认成 👍 / 👎 / ✋。':'这张照片里没有找到可用的手。';return}if(counts.yes>counts.no)verdict.textContent=`赞成比反对多 ${counts.yes-counts.no} 票。${counts.hold?`另外 ${counts.hold} 票保留。`:''}`;else if(counts.no>counts.yes)verdict.textContent=`反对比赞成多 ${counts.no-counts.yes} 票。${counts.hold?`另外 ${counts.hold} 票保留。`:''}`;else verdict.textContent=`赞成和反对一样多${counts.hold?`，另有 ${counts.hold} 票保留`:''}。`}
async function analyze(file){if(!file||!file.type.startsWith('image/'))return;setError('');intro.hidden=true;result.hidden=true;setBusy(true,'正在打开照片');try{const [img,rec]=await Promise.all([loadImage(file),loadRecognizer()]),src=makeSource(img),tiles=buildTiles(src.width,src.height),all=[];for(let ti=0;ti<tiles.length;ti++){setBusy(true,ti===0?'先看整张':`放大复核 ${ti} / ${tiles.length-1}`);const tile=tiles[ti],work=workFor(src,tile),out=await Promise.resolve(rec.recognize(work)),gestures=out?.gestures||[],landmarks=out?.landmarks||[],n=Math.max(gestures.length,landmarks.length);for(let i=0;i<n;i++){const lm=mapLandmarks(landmarks[i],tile,src.width,src.height),box=boxNorm(lm);if(!box)continue;const cls=classify(gestures[i],lm),votes={yes:0,no:0,hold:0};if(cls)votes[cls.key]=cls.conf;addDetection(all,{box,landmarks:lm,votes,maxConf:cls?.conf||0,views:1})}}
canvas.width=src.width;canvas.height=src.height;ctx.drawImage(src,0,0);const final=all.map(finalizeDetection),counts={yes:0,no:0,hold:0};let unknownCount=0,markIndex=0;for(const d of final){if(d.key){counts[d.key]++;drawMark(d.box,META[d.key],++markIndex)}else{unknownCount++;drawUnknown(d.box)}}setBusy(false);result.hidden=false;renderCounts(counts,final.length,unknownCount);lastFileName=`现场表决-${counts.yes}-${counts.no}-${counts.hold}.png`;window.scrollTo({top:0,behavior:'instant'})}catch(e){console.error(e);setBusy(false);intro.hidden=false;setError(e?.message==='image'?'这张照片没有成功打开。':'手势识别组件没有准备好。换个网络后再试。')}}
function pickCamera(){cameraInput.click()}
take.onclick=pickCamera;choose.onclick=()=>photoInput.click();cameraInput.onchange=()=>{analyze(cameraInput.files?.[0]);cameraInput.value=''};photoInput.onchange=()=>{analyze(photoInput.files?.[0]);photoInput.value=''};again.onclick=pickCamera;back.onclick=()=>{result.hidden=true;busy.hidden=true;intro.hidden=false;setError('');window.scrollTo({top:0,behavior:'instant'})};share.onclick=async()=>{const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)return;const file=new File([blob],lastFileName,{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file]});return}}catch{}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=lastFileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)};
})();