(()=>{
'use strict';
const $=s=>document.querySelector(s);
const home=$('#home'),start=$('#start'),error=$('#error'),setup=$('#setup'),exitSetup=$('#exitSetup'),video=$('#video'),readyText=$('#readyText'),test=$('#test');
const running=$('#running'),runSmall=$('#runSmall'),runTitle=$('#runTitle'),runHint=$('#runHint'),pulse=$('#pulse'),cancelRun=$('#cancelRun');
const result=$('#result'),resultBack=$('#resultBack'),again=$('#again'),verdict=$('#verdict'),resultText=$('#resultText'),lowValue=$('#lowValue'),returnValue=$('#returnValue'),chart=$('#chart'),copyResult=$('#copyResult'),resultNote=$('#resultNote');
const sample=$('#sample'),ctx=sample.getContext('2d',{willReadFrequently:true}),chartCtx=chart.getContext('2d');
let stream=null,raf=0,lastSampleAt=0,mode='idle',baseline=0,cal=[],timeline=[],darkSince=0,darkAt=0,recoverSince=0,minBrightness=255,maxAfterDark=0,testStarted=0,wake=null,lastOutcome=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
function setError(t=''){error.hidden=!t;error.textContent=t}
async function requestWake(){if(wake||!navigator.wakeLock?.request)return;try{wake=await navigator.wakeLock.request('screen');wake.addEventListener?.('release',()=>wake=null,{once:true})}catch{}}
async function releaseWake(){const w=wake;wake=null;if(w)try{await w.release()}catch{}}
async function openCamera(){setError('');stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});video.srcObject=stream;await video.play();home.hidden=true;result.hidden=true;running.hidden=true;setup.hidden=false;readyText.textContent='画面里能看到冰箱内部和灯光就可以。';mode='preview'}catch(e){console.error(e);setError('没有打开后置相机。请允许相机权限后再试。')}}
function stopCamera(){cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;mode='idle'}
function brightness(){if(video.readyState<2)return null;ctx.drawImage(video,0,0,sample.width,sample.height);const d=ctx.getImageData(0,0,sample.width,sample.height).data,vals=[];for(let y=5;y<sample.height-5;y+=2){for(let x=5;x<sample.width-5;x+=2){const i=(y*sample.width+x)*4,R=d[i],G=d[i+1],B=d[i+2];vals.push(.2126*R+.7152*G+.0722*B)}}return median(vals)}
function setPulse(v){const pct=baseline?clamp(v/baseline*100,0,120):0;pulse.firstElementChild.style.width=`${Math.min(100,pct)}%`}
function startSampling(){cancelAnimationFrame(raf);lastSampleAt=0;const loop=now=>{raf=requestAnimationFrame(loop);if(now-lastSampleAt<72)return;lastSampleAt=now;const v=brightness();if(v==null)return;handleBrightness(now,v)};raf=requestAnimationFrame(loop)}
function handleBrightness(now,v){if(mode==='calibrating'){cal.push(v);if(cal.length>=15){baseline=median(cal.slice(-12));if(baseline<28){mode='preview';running.hidden=true;setup.hidden=false;readyText.textContent='画面太暗。把镜头朝向冰箱灯，再开始一次。';releaseWake();return}mode='waitClose';timeline=[];testStarted=performance.now();minBrightness=baseline;maxAfterDark=0;darkSince=0;darkAt=0;recoverSince=0;runSmall.textContent='现在';runTitle.textContent='关门';runHint.textContent='手机留在冰箱里。'}}
 if(!['waitClose','waitOpen'].includes(mode))return;const t=performance.now()-testStarted;timeline.push({t,v});if(timeline.length>260)timeline.shift();minBrightness=Math.min(minBrightness,v);setPulse(v);
 const ratio=v/Math.max(1,baseline);if(mode==='waitClose'){const dark=ratio<.48||(baseline-v>62&&ratio<.68);if(dark){if(!darkSince)darkSince=now;if(now-darkSince>=300){mode='waitOpen';darkAt=now;runSmall.textContent='已经变暗';runTitle.textContent='再打开门';runHint.textContent='把手机拿出来。';pulse.firstElementChild.style.background='#9bcf54'}}else darkSince=0;if(t>14000){finish(false,'timeout')}}
 else if(mode==='waitOpen'){maxAfterDark=Math.max(maxAfterDark,v);const recovered=now-darkAt>520&&v>baseline*.66;if(recovered){if(!recoverSince)recoverSince=now;if(now-recoverSince>=220)finish(true,'cycle')}else recoverSince=0;if(now-darkAt>18000)finish(true,'dark-only')}}
async function beginTest(){if(!stream)return;cal=[];baseline=0;timeline=[];mode='calibrating';setup.hidden=true;running.hidden=false;runSmall.textContent='准备';runTitle.textContent='别动';runHint.textContent='正在记住开门时的亮度。';pulse.firstElementChild.style.width='0';pulse.firstElementChild.style.background='#f5c928';await requestWake();startSampling()}
function drawChart(){const w=chart.width,h=chart.height;chartCtx.clearRect(0,0,w,h);chartCtx.fillStyle='#111';chartCtx.fillRect(0,0,w,h);if(timeline.length<2)return;const maxT=Math.max(...timeline.map(x=>x.t)),maxV=Math.max(baseline,...timeline.map(x=>x.v),1);chartCtx.strokeStyle='#30322e';chartCtx.lineWidth=1;const by=h-(baseline/maxV)*(h-26)-12;chartCtx.beginPath();chartCtx.moveTo(0,by);chartCtx.lineTo(w,by);chartCtx.stroke();chartCtx.strokeStyle='#f5c928';chartCtx.lineWidth=3;chartCtx.lineJoin='round';chartCtx.beginPath();timeline.forEach((p,i)=>{const x=p.t/maxT*w,y=h-(p.v/maxV)*(h-26)-12;i?chartCtx.lineTo(x,y):chartCtx.moveTo(x,y)});chartCtx.stroke()}
async function finish(ok,reason){if(!['waitClose','waitOpen'].includes(mode))return;mode='done';cancelAnimationFrame(raf);raf=0;const lowRatio=baseline?clamp(minBrightness/baseline,0,2):0;const returnRatio=baseline?clamp((maxAfterDark||timeline[timeline.length-1]?.v||0)/baseline,0,2):0;lastOutcome={ok,reason,lowRatio,returnRatio,baseline,minBrightness};running.hidden=true;result.hidden=false;setup.hidden=true;verdict.textContent=ok?'灭了':'没看到它灭';if(ok&&reason==='cycle')resultText.textContent='关门后画面明显变暗，重新开门后又恢复。';else if(ok)resultText.textContent='关门后画面持续变暗，记录到了灯光关闭。';else resultText.textContent='测试期间没有记录到明显的亮度下降。';lowValue.textContent=`${Math.round(lowRatio*100)}%`;returnValue.textContent=ok?`${Math.round(returnRatio*100)}%`:'—';resultNote.textContent=ok?(reason==='cycle'?'记录到完整的亮 → 暗 → 亮变化。':'记录到持续的亮 → 暗变化。'):'重新测试时，让镜头一直朝着冰箱内部的灯。';drawChart();stopCamera();await releaseWake();copyResult.textContent='复制结果'}
async function copyText(t){try{await navigator.clipboard.writeText(t);return true}catch{}try{const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}
async function copyOutcome(){if(!lastOutcome)return;const text=['灯灭了吗',`结果：${verdict.textContent}`,`关门最低亮度：${lowValue.textContent}`,lastOutcome.ok?`再开门亮度：${returnValue.textContent}`:'',resultText.textContent].filter(Boolean).join('\n');const ok=await copyText(text);copyResult.textContent=ok?'已复制':'复制失败';setTimeout(()=>copyResult.textContent='复制结果',900)}
function goHome(){stopCamera();releaseWake();setup.hidden=true;running.hidden=true;result.hidden=true;home.hidden=false;lastOutcome=null;window.scrollTo({top:0,behavior:'instant'})}
start.onclick=openCamera;exitSetup.onclick=goHome;test.onclick=beginTest;cancelRun.onclick=goHome;resultBack.onclick=goHome;again.onclick=openCamera;copyResult.onclick=copyOutcome;document.addEventListener('visibilitychange',()=>{if(document.hidden&&['calibrating','waitClose','waitOpen'].includes(mode)){cancelAnimationFrame(raf);raf=0}else if(!document.hidden&&stream&&['calibrating','waitClose','waitOpen'].includes(mode))startSampling()});window.addEventListener('pagehide',()=>{stopCamera();releaseWake()});
})();