const $=s=>document.querySelector(s);
const fileInput=$('#file'),home=$('#home'),work=$('#work'),back=$('#back'),change=$('#change'),fileName=$('#fileName'),error=$('#error');
const busy=$('#busy'),busyTitle=$('#busyTitle'),busyText=$('#busyText'),result=$('#result'),resultKicker=$('#resultKicker'),verdict=$('#verdict'),resultText=$('#resultText');
const facts=$('#facts'),entryCount=$('#entryCount'),checkedCount=$('#checkedCount'),issueCount=$('#issueCount'),issues=$('#issues'),issueMeta=$('#issueMeta'),issueList=$('#issueList'),okBlock=$('#okBlock'),okMeta=$('#okMeta'),okList=$('#okList'),copyBtn=$('#copy');
let pdfjs=null,lastReport=null,runId=0;
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).normalize('NFKC').toLowerCase().replace(/[·•…⋯.．。_—–\-:：;；,，、()（）【】\[\]《》<>“”"'‘’\s]/g,'').replace(/^第?[一二三四五六七八九十百千万\d]+(?:[章节篇部分卷])?/,'').replace(/^\d+(?:\.\d+){0,5}/,'');
function setError(t=''){error.hidden=!t;error.textContent=t}
function romanToInt(s){s=String(s||'').toUpperCase();if(!/^[IVXLCDM]+$/.test(s))return null;const v={I:1,V:5,X:10,L:50,C:100,D:500,M:1000};let n=0;for(let i=0;i<s.length;i++)n+=(v[s[i]]<(v[s[i+1]]||0))?-v[s[i]]:v[s[i]];return n>0?n:null}
function pageNum(s){const t=clean(s);if(/^\d{1,4}$/.test(t))return Number(t);return romanToInt(t)}
function dice(a,b){if(a===b)return 1;if(a.length<2||b.length<2)return 0;const m=new Map;for(let i=0;i<a.length-1;i++){const x=a.slice(i,i+2);m.set(x,(m.get(x)||0)+1)}let hit=0;for(let i=0;i<b.length-1;i++){const x=b.slice(i,i+2),c=m.get(x)||0;if(c){hit++;m.set(x,c-1)}}return 2*hit/((a.length-1)+(b.length-1))}
async function loadPdf(){if(pdfjs)return pdfjs;let last;for(const u of ['https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/legacy/build/pdf.mjs','https://unpkg.com/pdfjs-dist@4.10.38/legacy/build/pdf.mjs']){try{const m=await import(u);m.GlobalWorkerOptions.workerSrc=u.replace('pdf.mjs','pdf.worker.mjs');pdfjs=m;return m}catch(e){last=e}}throw last||new Error('pdfjs')}
function linesFromText(tc,width,height){const raw=(tc.items||[]).filter(x=>clean(x.str));raw.sort((a,b)=>(b.transform?.[5]||0)-(a.transform?.[5]||0)||(a.transform?.[4]||0)-(b.transform?.[4]||0));const groups=[];for(const item of raw){const x=item.transform?.[4]||0,y=item.transform?.[5]||0,w=Math.abs(item.width||0),h=Math.abs(item.height||item.transform?.[0]||10);let g=groups.find(z=>Math.abs(z.y-y)<=Math.max(2.6,Math.min(5,h*.34)));if(!g){g={y,items:[]};groups.push(g)}g.items.push({text:clean(item.str),x,y,w,h})}groups.sort((a,b)=>b.y-a.y);return groups.map(g=>{g.items.sort((a,b)=>a.x-b.x);let text='';let prev=null;for(const it of g.items){if(prev){const gap=it.x-(prev.x+prev.w);if(gap>Math.max(2.5,prev.h*.18))text+=' '}text+=it.text;prev=it}return{text:clean(text),y:g.y,width,height,items:g.items}}).filter(x=>x.text)}
function tocEntriesFromPage(page){const out=[];for(const line of page.lines){const its=line.items;let title='',num=null,raw='';if(its.length>=2){const last=its[its.length-1],n=pageNum(last.text);if(n&&n<=5000&&last.x>=page.width*.52){title=clean(its.slice(0,-1).map(x=>x.text).join(' ')).replace(/[.·…⋯．。_\-–—\s]+$/,'').trim();num=n;raw=last.text}}if(!num){const m=line.text.match(/^(.{2,150}?)(?:[.·…⋯．。_\-–—\s]{2,})(\d{1,4}|[ivxlcdmIVXLCDM]{1,8})\s*$/);if(m){const n=pageNum(m[2]);if(n&&n<=5000){title=clean(m[1]).replace(/[.·…⋯．。_\-–—\s]+$/,'').trim();num=n;raw=m[2]}}}if(!num||!title)continue;const n=norm(title);if(n.length<2||n.length>90||/^\d{4}$/.test(title))continue;out.push({title,listed:num,listedRaw:raw,pageIndex:page.index,titleNorm:n})}return out}
function printedNumber(page,label){if(label&&pageNum(label))return pageNum(label);const edge=page.lines.filter(l=>{const n=pageNum(l.text);if(!n)return false;const bottom=l.y<page.height*.17,top=l.y>page.height*.86;if(!bottom&&!top)return false;const it=l.items[0];return it&&it.x>page.width*.12&&it.x<page.width*.88});if(!edge.length)return null;edge.sort((a,b)=>{const ac=Math.abs((a.items[0].x||0)-page.width/2),bc=Math.abs((b.items[0].x||0)-page.width/2);return ac-bc});return pageNum(edge[0].text)}
function headingCandidates(page){return page.lines.filter((l,i)=>i<18&&l.y>page.height*.43&&l.text.length<180).map(l=>({text:l.text,n:norm(l.text),y:l.y})).filter(x=>x.n.length>=2)}
function titleScore(title,cand){const a=title.titleNorm,b=cand.n;if(!a||!b)return 0;if(a===b)return 1;if(b.startsWith(a)||a.startsWith(b))return .97;if(b.includes(a)||a.includes(b))return .93;const d=dice(a,b);return d>=.72?d:0}
function findHeading(entry,pages,tocSet,expectedIndex=null){let best=null;for(const p of pages){if(tocSet.has(p.index))continue;for(const c of p.headings){const s=titleScore(entry,c);if(s<.72)continue;const dist=expectedIndex==null?0:Math.abs(p.index-expectedIndex);const bonus=expectedIndex!=null?Math.max(0,.035-dist*.004):0;const score=s+bonus;if(!best||score>best.score||(Math.abs(score-best.score)<.001&&dist<best.dist))best={page:p,cand:c,score,dist}}}return best&&best.score>=.78?best:null}
function modeOffset(matches){const counts=new Map;for(const m of matches){if(!m.match)continue;const o=(m.match.page.index+1)-m.entry.listed;counts.set(o,(counts.get(o)||0)+1)}let best=null;for(const [offset,count] of counts)if(!best||count>best.count)best={offset,count};return best&&best.count>=2?best.offset:null}
async function readPdf(file,id){const lib=await loadPdf();if(id!==runId)return null;const data=new Uint8Array(await file.arrayBuffer());const doc=await lib.getDocument({data}).promise;const labels=await doc.getPageLabels().catch(()=>null);const pages=[];let textChars=0;for(let i=1;i<=doc.numPages;i++){if(id!==runId)return null;busyTitle.textContent='正在看目录';busyText.textContent=`${i} / ${doc.numPages} 页`;const page=await doc.getPage(i),vp=page.getViewport({scale:1}),tc=await page.getTextContent({includeMarkedContent:false});const lines=linesFromText(tc,vp.width,vp.height);textChars+=lines.reduce((n,l)=>n+l.text.length,0);const p={index:i-1,width:vp.width,height:vp.height,lines,label:labels?.[i-1]||null};p.printed=printedNumber(p,p.label);p.headings=headingCandidates(p);pages.push(p)}return{doc,pages,textChars}}
function detectToc(pages){const scan=pages.slice(0,Math.min(28,pages.length)),scores=scan.map(p=>({p,entries:tocEntriesFromPage(p)}));let tocPages=scores.filter(x=>x.entries.length>=3);if(!tocPages.length){const best=scores.sort((a,b)=>b.entries.length-a.entries.length)[0];if(best?.entries.length>=2)tocPages=[best]}if(!tocPages.length)return{entries:[],tocSet:new Set};const ids=tocPages.map(x=>x.p.index),min=Math.min(...ids),max=Math.max(...ids),selected=scores.filter(x=>x.p.index>=min&&x.p.index<=max&&x.entries.length>=2);const seen=new Set,entries=[];for(const x of selected)for(const e of x.entries){const k=`${e.titleNorm}|${e.listed}`;if(!seen.has(k)){seen.add(k);entries.push(e)}}return{entries,tocSet:new Set(selected.map(x=>x.p.index))}}
function nearestExpected(entry,pages){const hit=pages.find(p=>p.printed===entry.listed);return hit?.index??null}
function buildReport(pages,entries,tocSet){const matches=entries.map(entry=>{const expected=nearestExpected(entry,pages);return{entry,match:findHeading(entry,pages,tocSet,expected)}});const inferred=modeOffset(matches);const rows=[];for(const m of matches){if(!m.match){rows.push({kind:'unfound',title:m.entry.title,listed:m.entry.listed,actual:null});continue}const p=m.match.page,actual=p.printed??(inferred==null?null:(p.index+1-inferred));if(actual==null){const expected=nearestExpected(m.entry,pages);if(expected!=null&&expected===p.index)rows.push({kind:'ok',title:m.entry.title,listed:m.entry.listed,actual:m.entry.listed});else rows.push({kind:'unconfirmed',title:m.entry.title,listed:m.entry.listed,actual:null});continue}rows.push({kind:actual===m.entry.listed?'ok':'mismatch',title:m.entry.title,listed:m.entry.listed,actual})}return{rows,inferred}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderReport(report){lastReport=report;busy.hidden=true;result.hidden=false;const rows=report.rows,good=rows.filter(x=>x.kind==='ok'),bad=rows.filter(x=>x.kind==='mismatch'),unknown=rows.filter(x=>x.kind==='unfound'||x.kind==='unconfirmed'),checked=good.length+bad.length;entryCount.textContent=String(rows.length);checkedCount.textContent=String(checked);issueCount.textContent=String(bad.length+unknown.length);facts.hidden=false;if(bad.length){resultKicker.textContent='目录';verdict.textContent=`${bad.length} 处页码不对`;resultText.textContent=unknown.length?`另外 ${unknown.length} 项没确认。`:''}else if(unknown.length){resultKicker.textContent='目录';verdict.textContent=`${unknown.length} 项没确认`;resultText.textContent='其余已核对的页码都对得上。'}else{resultKicker.textContent='目录';verdict.textContent='都对得上';resultText.textContent=''}resultText.hidden=!resultText.textContent;const problem=[...bad,...unknown];issues.hidden=!problem.length;issueMeta.textContent=problem.length?`${problem.length} 项`:'';issueList.innerHTML=problem.map(x=>x.kind==='mismatch'?`<div class="issue-row"><div><strong>${esc(x.title)}</strong><small>目录写 ${x.listed}</small></div><div class="page-shift"><b>${x.actual}</b><span>正文页码</span></div></div>`:`<div class="issue-row unfound"><div><strong>${esc(x.title)}</strong><small>目录写 ${x.listed}</small></div><div class="page-shift"><b>没找到</b><span>正文标题</span></div></div>`).join('');okBlock.hidden=!good.length;okMeta.textContent=good.length?`${good.length} 项`:'';okList.innerHTML=good.slice(0,80).map(x=>`<div class="ok-row"><div><strong>${esc(x.title)}</strong></div><div class="page-shift"><b>${x.listed}</b></div></div>`).join('');copyBtn.hidden=!problem.length}
async function process(file){if(!file)return;if(file.type&&file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name)){setError('请选择 PDF。');return}const id=++runId;setError('');home.hidden=true;work.hidden=false;result.hidden=true;busy.hidden=false;facts.hidden=true;issues.hidden=true;okBlock.hidden=true;copyBtn.hidden=true;fileName.textContent=file.name;busyTitle.textContent='正在打开';busyText.textContent='';try{const parsed=await readPdf(file,id);if(!parsed||id!==runId)return;if(parsed.textChars<80){busy.hidden=true;result.hidden=false;resultKicker.textContent='目录';verdict.textContent='没有可读文字';resultText.hidden=false;resultText.textContent='这份 PDF 像是扫描件，暂时不能核对目录。';lastReport=null;return}const {entries,tocSet}=detectToc(parsed.pages);if(entries.length<2){busy.hidden=true;result.hidden=false;resultKicker.textContent='目录';verdict.textContent='没找到目录';resultText.hidden=false;resultText.textContent='没有找到连续的“标题 + 页码”目录项目。';lastReport=null;return}busyTitle.textContent='正在对页码';busyText.textContent=`找到 ${entries.length} 项`;await new Promise(r=>setTimeout(r,0));const report=buildReport(parsed.pages,entries,tocSet);renderReport(report)}catch(e){console.error(e);if(id!==runId)return;work.hidden=true;home.hidden=false;setError('这份 PDF 没有成功打开。')}}
fileInput.onchange=()=>{const f=fileInput.files?.[0];if(f)process(f);fileInput.value=''};change.onclick=()=>fileInput.click();back.onclick=()=>{runId++;work.hidden=true;home.hidden=false;lastReport=null;window.scrollTo({top:0,behavior:'instant'})};copyBtn.onclick=async()=>{if(!lastReport)return;const bad=lastReport.rows.filter(x=>x.kind!=='ok');const text=['目录对账',...bad.map(x=>x.kind==='mismatch'?`${x.title}：目录 ${x.listed} → 正文 ${x.actual}`:`${x.title}：目录 ${x.listed} → 没找到正文标题`)].join('\n');try{await navigator.clipboard.writeText(text);copyBtn.textContent='已复制';setTimeout(()=>copyBtn.textContent='复制结果',900)}catch{copyBtn.textContent='复制失败';setTimeout(()=>copyBtn.textContent='复制结果',900)}};