(()=>{
'use strict';
const $=s=>document.querySelector(s);const home=$('#home'),start=$('#start'),error=$('#error'),watch=$('#watch'),video=$('#video'),sample=$('#sample'),sctx=sample.getContext('2d',{willReadFrequently:true}),exit=$('#exit'),reset=$('#reset'),target=$('#target'),tapTip=$('#tapTip'),state=$('#state'),currentEl=$('#current'),typicalEl=$('#typical'),intervalEl=$('#interval'),roundsEl=$('#rounds'),hint=$('#hint');
let stream=null,raf=0,lastFrame=0,targetN=null,signals=[],lampState=null,current=0,lastRise=0,riseTimes=[],roundRise=[],rounds=[],roundIntervals=[],finalized=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=s.length>>1;return s.length%2?s[m]:(s[m-1]+s[m])/2};
function setError(t=''){error.hidden=!t;error.textContent=t}
function percentile(a,p){if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=clamp(Math.floor((s.length-1)*p),0,s.length-1);return s[i]}
function resetCounts(keepTarget=true){signals=[];lampState=null;current=0;lastRise=0;riseTimes=[];roundRise=[];rounds=[];roundIntervals=[];finalized=false;currentEl.textContent='0';typicalEl.textContent='—';intervalEl.textContent='—';roundsEl.textContent='0 轮';hint.textContent=targetN?'正在等它形成第一轮。':'选中指示灯后，保持镜头大致不动。';if(!keepTarget){targetN=null;target.hidden=true;tapTip.hidden=false;state.textContent='点一下正在闪的灯'}}
function modeCount(a){if(!a.length)return null;const m=new Map();for(const v of a)m.set(v,(m.get(v)||0)+1);return[...m.entries()].sort((x,y)=>y[1]-x[1]||y[0]-x[0])[0][0]}
function updateStats(){currentEl.textContent=String(current);roundsEl.textContent=`${rounds.length} 轮`;if(rounds.length)typicalEl.textContent=`${modeCount(rounds)} 下`;const ints=roundIntervals.filter(x=>x>90&&x<8000);intervalEl.textContent=ints.length?`${(median(ints)/1000).toFixed(2)}s`:'—'}
function cycleGap(){const ints=roundIntervals.filter(x=>x>100&&x<5000);if(!ints.length)return 1900;const base=median([...ints].sort((a,b)=>a-b).slice(0,Math.max(1,Math.ceil(ints.length*.65))));return clamp(base*2.45,1100,4800)}
function finishRound(now){if(!current||finalized)return;rounds.push(current);if(roundRise.length>1)for(let i=1;i<roundRise.length;i++)roundIntervals.push(roundRise[i]-roundRise[i-1]);current=0;roundRise=[];finalized=true;updateStats();hint.textContent=`上一轮 ${rounds.at(-1)} 下。继续看下一轮。`;state.textContent='轮次已分开'}
function rise(now){if(lastRise){const gap=now-lastRise;if(current&&gap>cycleGap()){finishRound(now);finalized=false}else if(current)roundIntervals.push(gap)}if(finalized)finalized=false;current++;roundRise.push(now);riseTimes.push(now);lastRise=now;updateStats();state.textContent='看到了闪光';hint.textContent='继续保持，大间隔会自动分成下一轮。'}
function videoPoint(clientX,clientY){const r=video.getBoundingClientRect(),vw=video.videoWidth||r.width,vh=video.videoHeight||r.height,bar=r.width/r.height,varr=vw/vh;let nx,ny;if(varr>bar){const scale=r.height/vh,dw=vw*scale,crop=(dw-r.width)/2;nx=(clientX-r.left+crop)/dw;ny=(clientY-r.top)/r.height}else{const scale=r.width/vw,dh=vh*scale,crop=(dh-r.height)/2;nx=(clientX-r.left)/r.width;ny=(clientY-r.top+crop)/dh}return{x:clamp(nx,0,1),y:clamp(ny,0,1)}}
function placeTarget(clientX,clientY){targetN=videoPoint(clientX,clientY);target.style.left=`${clientX}px`;target.style.top=`${clientY}px`;target.hidden=false;tapTip.hidden=true;state.textContent='正在看这颗灯';resetCounts(true)}
function brightnessAt(){const vw=video.videoWidth,vh=video.videoHeight;if(!vw||!vh||!targetN)return null;const max=360,scale=Math.min(1,max/Math.max(vw,vh));sample.width=Math.max(2,Math.round(vw*scale));sample.height=Math.max(2,Math.round(vh*scale));sctx.drawImage(video,0,0,sample.width,sample.height);const cx=Math.round(targetN.x*sample.width),cy=Math.round(targetN.y*sample.height),r=Math.max(3,Math.round(Math.min(sample.width,sample.height)*.025)),R=Math.max(r+3,Math.round(r*2.35)),x0=clamp(cx-R,0,sample.width-1),y0=clamp(cy-R,0,sample.height-1),x1=clamp(cx+R,1,sample.width),y1=clamp(cy+R,1,sample.height),w=x1-x0,h=y1-y0;if(w<2||h<2)return null;const d=sctx.getImageData(x0,y0,w,h).data;let inner=0,ic=0,outer=0,oc=0,k=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++,k+=4){const dx=x+x0-cx,dy=y+y0-cy,dd=Math.hypot(dx,dy);const lum=.299*d[k]+.587*d[k+1]+.114*d[k+2],v=Math.max(d[k],d[k+1],d[k+2])*.55+lum*.45;if(dd<=r){inner+=v;ic++}else if(dd<=R){outer+=v;oc++}}return ic&&oc?inner/ic-outer/oc:null}
function tick(now){raf=requestAnimationFrame(tick);if(document.hidden||video.readyState<2||!targetN||now-lastFrame<33)return;lastFrame=now;const sig=brightnessAt();if(sig==null)return;signals.push(sig);if(signals.length>150)signals.shift();if(signals.length<24){state.textContent='正在适应亮度';return}const low=percentile(signals,.18),high=percentile(signals,.86),range=high-low;if(range<5.5){state.textContent='还在等它明显闪一下';if(current&&lastRise&&now-lastRise>cycleGap())finishRound(now);return}const hi=low+range*.67,lo=low+range*.39;if(lampState==null){lampState=sig>hi;state.textContent='已经锁定亮暗变化'}else if(!lampState&&sig>hi){lampState=true;rise(now)}else if(lampState&&sig<lo)lampState=false;if(current&&lastRise&&now-lastRise>cycleGap())finishRound(now)}
async function openCamera(){setError('');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:false});video.srcObject=stream;await video.play();home.hidden=true;watch.hidden=false;resetCounts(false);cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)}catch(e){console.error(e);setError('没有成功打开后置相机。请允许相机权限后再试。')}}
function closeCamera(){cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;watch.hidden=true;home.hidden=false;resetCounts(false)}
start.onclick=openCamera;exit.onclick=closeCamera;reset.onclick=()=>resetCounts(true);watch.addEventListener('pointerup',e=>{if(e.target.closest('.watch-top')||e.target.closest('.panel'))return;placeTarget(e.clientX,e.clientY)});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else if(stream){video.play().catch(()=>{});raf=requestAnimationFrame(tick)}});window.addEventListener('pagehide',closeCamera);
})();