(()=>{
'use strict';
const $=s=>document.querySelector(s);
const pick=$('#pick'),filesInput=$('#files'),error=$('#error'),intro=$('#intro'),busy=$('#busy'),busyText=$('#busyText'),result=$('#result'),back=$('#back'),again=$('#again'),winnerName=$('#winnerName'),winnerTime=$('#winnerTime'),warning=$('#warning'),versionList=$('#versionList'),duplicates=$('#duplicates'),duplicateCount=$('#duplicateCount'),duplicateList=$('#duplicateList');
let items=[],pdfjs=null,zipLib=null;
const FINAL_RE=/(?:^|[\s_\-.()（）\[\]【】])(final|finalized|最终|終版|终版|定稿|最后|最後|最新版|finalfinal)(?:$|[\s_\-.()（）\[\]【】\d])/i;
function setError(t=''){error.hidden=!t;error.textContent=t}
function cleanName(n){return String(n||'').replace(/\.[^.]+$/,'')}
function fmtTime(t){if(!t)return'没有可用修改时间';const d=new Date(t),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}/${pad(d.getMonth()+1)}/${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`}
function fmtSize(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(n<10240?1:0)} KB`;return`${(n/1048576).toFixed(n<10485760?1:0)} MB`}
async function digest(buf){const h=await crypto.subtle.digest('SHA-256',buf),a=new Uint8Array(h);return[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function loadZip(){if(zipLib)return zipLib;for(const u of ['https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm','https://esm.sh/jszip@3.10.1']){try{const m=await import(u);zipLib=m.default||m;return zipLib}catch{}}throw new Error('zip')}
async function loadPdf(){if(pdfjs)return pdfjs;for(const u of ['https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/legacy/build/pdf.mjs','https://unpkg.com/pdfjs-dist@6.2.108/legacy/build/pdf.mjs']){try{pdfjs=await import(u);pdfjs.GlobalWorkerOptions.workerSrc=u.replace('pdf.mjs','pdf.worker.mjs');return pdfjs}catch{}}throw new Error('pdf')}
function normalizeText(t){return String(t||'').normalize('NFKC').replace(/\s+/g,' ').trim()}
function paragraphs(t){return String(t||'').replace(/\r/g,'').split(/\n+|(?<=[。！？.!?])\s+/).map(x=>normalizeText(x)).filter(x=>x.length>=3)}
async function textFromDocx(buf){const JSZip=await loadZip(),zip=await JSZip.loadAsync(buf),xml=await zip.file('word/document.xml')?.async('text');if(!xml)return'';const d=new DOMParser().parseFromString(xml,'application/xml'),out=[];for(const p of d.querySelectorAll('w\\:p,p')){const t=[...p.querySelectorAll('w\\:t,t')].map(x=>x.textContent).join('').trim();if(t)out.push(t)}return out.join('\n')}
async function textFromXlsx(buf){const JSZip=await loadZip(),zip=await JSZip.loadAsync(buf),shared=[];const ss=await zip.file('xl/sharedStrings.xml')?.async('text');if(ss){const d=new DOMParser().parseFromString(ss,'application/xml');for(const si of d.querySelectorAll('si'))shared.push([...si.querySelectorAll('t')].map(x=>x.textContent).join(''))}const names=Object.keys(zip.files).filter(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x)).sort(),out=[];for(const name of names.slice(0,8)){const xml=await zip.file(name)?.async('text');if(!xml)continue;const d=new DOMParser().parseFromString(xml,'application/xml');for(const r of d.querySelectorAll('row')){const cells=[];for(const c of r.querySelectorAll('c')){const ty=c.getAttribute('t'),v=c.querySelector('v')?.textContent||'',inline=[...c.querySelectorAll('is t')].map(x=>x.textContent).join('');cells.push(ty==='s'?shared[Number(v)]??v:ty==='inlineStr'?inline:v)}if(cells.some(Boolean))out.push(cells.join('\t'))}}return out.join('\n')}
async function textFromPptx(buf){const JSZip=await loadZip(),zip=await JSZip.loadAsync(buf),names=Object.keys(zip.files).filter(x=>/^ppt\/slides\/slide\d+\.xml$/.test(x)).sort((a,b)=>Number(a.match(/\d+/)?.[0])-Number(b.match(/\d+/)?.[0])),out=[];for(const name of names){const xml=await zip.file(name)?.async('text');if(!xml)continue;const d=new DOMParser().parseFromString(xml,'application/xml'),t=[...d.querySelectorAll('a\\:t,t')].map(x=>x.textContent).join(' ').trim();if(t)out.push(t)}return out.join('\n')}
async function textFromPdf(buf){const lib=await loadPdf(),doc=await lib.getDocument({data:new Uint8Array(buf)}).promise,out=[];for(let p=1;p<=Math.min(30,doc.numPages);p++){const page=await doc.getPage(p),tc=await page.getTextContent();out.push(tc.items.map(x=>x.str).join(' '))}return out.join('\n')}
async function extractText(file,buf){const n=file.name.toLowerCase();try{if(/\.(txt|md|markdown|csv|tsv|json|xml|html|htm|js|ts|css|py|java|c|cpp|h|log)$/i.test(n))return new TextDecoder('utf-8').decode(buf);if(/\.docx$/i.test(n))return await textFromDocx(buf);if(/\.xlsx$/i.test(n))return await textFromXlsx(buf);if(/\.pptx$/i.test(n))return await textFromPptx(buf);if(/\.pdf$/i.test(n))return await textFromPdf(buf)}catch(e){console.warn('text extract',file.name,e)}return''}
function shingleSet(t){const s=normalizeText(t).replace(/\s+/g,'').toLowerCase(),set=new Set(),step=Math.max(1,Math.ceil(Math.max(1,s.length-7)/5000));for(let i=0;i<=s.length-7;i+=step)set.add(s.slice(i,i+7));return set}
function similarity(a,b){if(!a||!b)return null;const A=shingleSet(a),B=shingleSet(b);if(!A.size||!B.size)return null;let inter=0;for(const x of A)if(B.has(x))inter++;return inter/(A.size+B.size-inter)}
function paragraphDelta(a,b){if(!a||!b)return null;const A=new Set(paragraphs(a)),B=new Set(paragraphs(b));let add=0,del=0;for(const x of B)if(!A.has(x))add++;for(const x of A)if(!B.has(x))del++;return{add,del}}
async function inspect(file,index){const buf=await file.arrayBuffer(),rawHash=file.size<=120*1024*1024?await digest(buf):null,text=await extractText(file,buf),norm=normalizeText(text),textHash=norm?await digest(new TextEncoder().encode(norm)):null;return{file,index,name:file.name,modified:file.lastModified||0,size:file.size,rawHash,text,textHash}}
function groupDuplicates(arr){const map=new Map();for(const x of arr){const key=x.textHash?`t:${x.textHash}`:x.rawHash?`r:${x.rawHash}`:null;if(!key)continue;if(!map.has(key))map.set(key,[]);map.get(key).push(x)}return[...map.values()].filter(g=>g.length>1)}
function render(){const sorted=[...items].sort((a,b)=>b.modified-a.modified||b.size-a.size),winner=sorted[0];winnerName.textContent=winner.name;winnerTime.textContent=`${fmtTime(winner.modified)} · ${fmtSize(winner.size)}`;const namedFinal=sorted.filter(x=>FINAL_RE.test(` ${cleanName(x.name)} `)),olderFinal=namedFinal.find(x=>x!==winner&&x.modified<winner.modified);warning.hidden=true;if(olderFinal){warning.hidden=false;warning.textContent=`“${olderFinal.name}”名字里写着最终版，但它比“${winner.name}”更早。`}else if(namedFinal.length&& !FINAL_RE.test(` ${cleanName(winner.name)} `)){warning.hidden=false;warning.textContent=`名字最像“最终版”的那份并不是最后修改的；最后改的是“${winner.name}”。`}
  versionList.innerHTML=sorted.map((x,i)=>{const older=sorted[i+1],sim=older?similarity(older.text,x.text):null,delta=older?paragraphDelta(older.text,x.text):null;let detail=`${fmtTime(x.modified)} · ${fmtSize(x.size)}`;if(older&&sim!=null){detail+=` · 与下一份可读文字 ${Math.round(sim*100)}% 相似`;if(delta&&(delta.add||delta.del))detail+=` · +${delta.add} / −${delta.del} 段`}else if(i<sorted.length-1&&!x.text)detail+=' · 正文不可读取';return`<div class="version"><i>${String(i+1).padStart(2,'0')}</i><span><strong>${x.name}</strong><small>${detail}</small></span><em>${i===0?'最后修改':''}</em></div>`}).join('');
  const groups=groupDuplicates(sorted);duplicates.hidden=!groups.length;duplicateCount.textContent=groups.length?`${groups.length} 组`:'0';duplicateList.innerHTML=groups.map(g=>`<div class="duplicate-group"><strong>${g.length} 个名字，其实内容一样</strong><p>${g.map(x=>x.name).join('　·　')}</p></div>`).join('')
}
async function openFiles(list){const fs=[...list].filter(f=>f&&f.name);if(fs.length<2){setError('至少选两个版本。');return}if(fs.length>20){setError('一次先选 2–20 个版本。');return}setError('');intro.hidden=true;result.hidden=true;busy.hidden=false;try{const out=[];for(let i=0;i<fs.length;i++){busyText.textContent=`正在看第 ${i+1} / ${fs.length} 份`;out.push(await inspect(fs[i],i))}items=out;busy.hidden=true;result.hidden=false;render();window.scrollTo({top:0,behavior:'instant'})}catch(e){console.error(e);busy.hidden=true;intro.hidden=false;setError('这组文件没有成功比完。')}}
pick.onclick=()=>filesInput.click();filesInput.onchange=()=>{openFiles(filesInput.files);filesInput.value=''};again.onclick=()=>filesInput.click();back.onclick=()=>{result.hidden=true;busy.hidden=true;intro.hidden=false;items=[];window.scrollTo({top:0,behavior:'instant'})};
})();