(()=>{
'use strict';
const $=s=>document.querySelector(s);
const home=$('#home'),take=$('#take'),choose=$('#choose'),cameraInput=$('#cameraInput'),photoInput=$('#photoInput'),error=$('#error');
const busy=$('#busy'),busyText=$('#busyText'),result=$('#result'),back=$('#back'),again=$('#again'),verdictEl=$('#verdict'),comparison=$('#comparison'),canvas=$('#canvas'),ranking=$('#ranking'),faceCount=$('#faceCount'),copyResult=$('#copyResult'),work=$('#work');
const ctx=canvas.getContext('2d'),wctx=work.getContext('2d',{willReadFrequently:true});
let landmarker=null,url='',faces=[],lastText='';
const dist=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.y||0)-(b?.y||0));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function setError(t=''){error.hidden=!t;error.textContent=t}
function loadImage(src){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=src})}
async function loadLandmarker(){if(landmarker)return landmarker;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,L=mod.FaceLandmarker||mod.default?.FaceLandmarker;if(!F||!L)throw new Error('module');const vision=await F.forVisionTasks(s.wasm),base={modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'};try{landmarker=await L.createFromOptions(vision,{baseOptions:{...base,delegate:'GPU'},runningMode:'IMAGE',numFaces:12,outputFaceBlendshapes:false,minFaceDetectionConfidence:.16,minFacePresenceConfidence:.16,minTrackingConfidence:.16})}catch{landmarker=await L.createFromOptions(vision,{baseOptions:base,runningMode:'IMAGE',numFaces:12,outputFaceBlendshapes:false,minFaceDetectionConfidence:.20,minFacePresenceConfidence:.20,minTrackingConfidence:.20})}return landmarker}catch(e){last=e;landmarker=null}}throw last||new Error('face')}
function faceMetric(lm){const left=lm?.[234],right=lm?.[454],top=lm?.[10],chin=lm?.[152],nose=lm?.[1];if(!left||!right||!top||!chin||!nose)return null;const width=dist(left,right),height=dist(top,chin);if(width<.025||height<.035)return null;let minX=1,minY=1,maxX=0,maxY=0;for(const p of lm){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const edge=minX<-.01||minY<-.01||maxX>1.01||maxY>1.01;return{lm,left,right,top,chin,nose,width,height,area:width*height,cx:(left.x+right.x)/2,cy:(top.y+chin.y)/2,minX,minY,maxX,maxY,edge}}
function drawOverlay(img){canvas.width=work.width;canvas.height=work.height;ctx.drawImage(img,0,0,canvas.width,canvas.height);ctx.save();ctx.lineWidth=Math.max(2,Math.round(Math.min(canvas.width,canvas.height)*.003));ctx.textAlign='center';ctx.textBaseline='middle';for(const f of faces){const x=f.cx*canvas.width,y=f.cy*canvas.height,rx=f.width*canvas.width*.62,ry=f.height*canvas.height*.57;ctx.strokeStyle=f.rank===1?'#d8d7ff':'rgba(242,240,233,.82)';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.stroke();const r=Math.max(16,Math.min(27,Math.min(canvas.width,canvas.height)*.024)),labelY=Math.max(r+4,y-ry-r*.25);ctx.fillStyle=f.rank===1?'#d8d7ff':'#10110f';ctx.beginPath();ctx.arc(x,labelY,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=f.rank===1?'#10110f':'rgba(242,240,233,.9)';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle=f.rank===1?'#10110f':'#f2f0e9';ctx.font=`800 ${Math.round(r*.82)}px -apple-system,BlinkMacSystemFont,"PingFang SC",Arial`;ctx.fillText(String(f.no),x,labelY+1)}ctx.restore()}
function renderResult(img){const sorted=[...faces].sort((a,b)=>b.area-a.area);sorted.forEach((f,i)=>f.rank=i+1);const top=sorted[0],second=sorted[1],gap=(top.area/second.area-1)*100;drawOverlay(img);faceCount.textContent=`${faces.length} 张脸`;if(gap<3){verdictEl.textContent='差不多大';comparison.textContent=`${top.no} 号和 ${second.no} 号只差 ${Math.abs(gap).toFixed(1)}%`}else{verdictEl.textContent=`${top.no} 号最大`;comparison.textContent=faces.length===2?`比 ${second.no} 号大 ${Math.round(gap)}%`:`比第二名大 ${Math.round(gap)}%`}ranking.innerHTML=sorted.map(f=>{const rel=f.area/top.area*100;return`<li><i>${f.no}</i><span>${f.rank===1?'这张照片里最大':`第 ${f.rank}`}${f.edge?'<small>脸靠近照片边缘</small>':''}</span><strong>${rel.toFixed(rel>99?0:1)}%</strong></li>`}).join('');lastText=['谁脸大',`结果：${verdictEl.textContent}`,comparison.textContent,...sorted.map(f=>`${f.no} 号：${(f.area/top.area*100).toFixed(1)}%`),'结果只代表这张照片里的可见脸部大小。'].join('\n');busy.hidden=true;result.hidden=false;home.hidden=true;window.scrollTo({top:0,behavior:'instant'})}
async function analyze(file){if(!file||!file.type.startsWith('image/')){setError('请选择一张照片。');return}setError('');home.hidden=true;result.hidden=true;busy.hidden=false;busyText.textContent='先找人';try{if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);const img=await loadImage(url),max=1800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));work.width=Math.max(1,Math.round(img.naturalWidth*scale));work.height=Math.max(1,Math.round(img.naturalHeight*scale));wctx.drawImage(img,0,0,work.width,work.height);busyText.textContent='正在量脸';const L=await loadLandmarker(),r=L.detect(work),raw=(r?.faceLandmarks||[]).map(faceMetric).filter(Boolean);if(raw.length<2){busy.hidden=true;home.hidden=false;setError(raw.length===1?'这张照片只找到一张完整的脸。':'这张照片没有找到两张完整的脸。');return}raw.sort((a,b)=>a.cx-b.cx);faces=raw.map((f,i)=>({...f,no:i+1,rank:0}));renderResult(img)}catch(e){console.error(e);busy.hidden=true;home.hidden=false;setError('这张照片没有成功分析。再换一张试试。')}}
async function copyText(t){try{await navigator.clipboard.writeText(t);return true}catch{}try{const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}
async function copy(){if(!lastText)return;const ok=await copyText(lastText);copyResult.textContent=ok?'已复制':'复制失败';setTimeout(()=>copyResult.textContent='复制结果',900)}
function reset(){busy.hidden=true;result.hidden=true;home.hidden=false;setError('');faces=[];lastText='';if(url){URL.revokeObjectURL(url);url=''}window.scrollTo({top:0,behavior:'instant'})}
take.onclick=()=>cameraInput.click();choose.onclick=()=>photoInput.click();cameraInput.onchange=()=>{analyze(cameraInput.files?.[0]);cameraInput.value=''};photoInput.onchange=()=>{analyze(photoInput.files?.[0]);photoInput.value=''};back.onclick=reset;again.onclick=()=>photoInput.click();copyResult.onclick=copy;window.addEventListener('pagehide',()=>{if(url)URL.revokeObjectURL(url)});
})();