(()=>{
'use strict';
const $=s=>document.querySelector(s);
const pick=$('#pick'),filesInput=$('#files'),error=$('#error'),intro=$('#intro'),busy=$('#busy'),busyText=$('#busyText'),result=$('#result'),back=$('#back'),again=$('#again'),winnerImg=$('#winnerImg'),winnerName=$('#winnerName'),winnerMeta=$('#winnerMeta'),list=$('#list'),share=$('#share');
let landmarker=null,items=[],urls=[];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function setError(t=''){error.hidden=!t;error.textContent=t}
function cleanUrls(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[]}
async function loadLandmarker(){if(landmarker)return landmarker;const sources=[{js:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'},{js:'https://esm.sh/@mediapipe/tasks-vision@0.10.35',wasm:'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'}];let last=null;for(const s of sources){try{const mod=await import(s.js),F=mod.FilesetResolver||mod.default?.FilesetResolver,L=mod.FaceLandmarker||mod.default?.FaceLandmarker;if(!F||!L)throw new Error('module');const vision=await F.forVisionTasks(s.wasm),base={modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'};try{landmarker=await L.createFromOptions(vision,{baseOptions:{...base,delegate:'GPU'},runningMode:'IMAGE',numFaces:12,outputFaceBlendshapes:true,minFaceDetectionConfidence:.14,minFacePresenceConfidence:.14,minTrackingConfidence:.14})}catch{landmarker=await L.createFromOptions(vision,{baseOptions:base,runningMode:'IMAGE',numFaces:12,outputFaceBlendshapes:true,minFaceDetectionConfidence:.18,minFacePresenceConfidence:.18,minTrackingConfidence:.18})}return landmarker}catch(e){last=e;landmarker=null}}throw last||new Error('face')}
function loadImage(url){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url})}
function canvasFor(img,max=1400){const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext('2d',{willReadFrequently:true}).drawImage(img,0,0,c.width,c.height);return c}
function blinkMap(cats=[]){const m={};for(const c of cats){const k=String(c.categoryName||c.displayName||'').replace(/[_\s-]/g,'').toLowerCase();m[k]=Number(c.score)||0}return{l:m.eyeblinkleft||0,r:m.eyeblinkright||0}}
function boxOf(lm,w,h){let minX=1,maxX=0,minY=1,maxY=0;for(const p of lm||[]){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const pad=.08;return{x:clamp((minX-pad*(maxX-minX))*w,0,w-1),y:clamp((minY-pad*(maxY-minY))*h,0,h-1),w:clamp((maxX-minX)*(1+2*pad)*w,1,w),h:clamp((maxY-minY)*(1+2*pad)*h,1,h)}}
function lapVar(ctx,x,y,w,h){const sw=Math.max(20,Math.min(180,Math.round(w))),sh=Math.max(20,Math.min(180,Math.round(h))),c=document.createElement('canvas');c.width=sw;c.height=sh;const cc=c.getContext('2d',{willReadFrequently:true});cc.drawImage(ctx.canvas,x,y,w,h,0,0,sw,sh);const d=cc.getImageData(0,0,sw,sh).data,g=new Float32Array(sw*sh);for(let i=0,j=0;i<d.length;i+=4,j++)g[j]=.299*d[i]+.587*d[i+1]+.114*d[i+2];let sum=0,sum2=0,n=0;for(let yy=1;yy<sh-1;yy++)for(let xx=1;xx<sw-1;xx++){const i=yy*sw+xx,v=4*g[i]-g[i-1]-g[i+1]-g[i-sw]-g[i+sw];sum+=v;sum2+=v*v;n++}if(!n)return 0;const mean=sum/n;return Math.max(0,sum2/n-mean*mean)}
function exposure(ctx){const {width:w,height:h}=ctx.canvas,sw=Math.min(220,w),sh=Math.min(220,h),c=document.createElement('canvas');c.width=sw;c.height=sh;const cc=c.getContext('2d',{willReadFrequently:true});cc.drawImage(ctx.canvas,0,0,w,h,0,0,sw,sh);const d=cc.getImageData(0,0,sw,sh).data;let clip=0,total=d.length/4;for(let i=0;i<d.length;i+=4){const y=.299*d[i]+.587*d[i+1]+.114*d[i+2];if(y<8||y>247)clip++}return clip/total}
async function analyze(file,index){const url=URL.createObjectURL(file);urls.push(url);const img=await loadImage(url),c=canvasFor(img),ctx=c.getContext('2d',{willReadFrequently:true}),r=landmarker.detect(c),faces=r?.faceLandmarks||[],sharps=[],faceData=[];for(let i=0;i<faces.length;i++){const b=boxOf(faces[i],c.width,c.height),bl=blinkMap(r?.faceBlendshapes?.[i]?.categories||[]),blink=Math.max(bl.l,bl.r),state=blink>.58?'closed':blink>.38?'uncertain':'open',sharp=lapVar(ctx,b.x,b.y,b.w,b.h);sharps.push(sharp);faceData.push({blink,state,sharp})}const sharp=sharps.length?sharps.sort((a,b)=>a-b)[Math.floor((sharps.length-1)*.25)]:lapVar(ctx,0,0,c.width,c.height),closed=faceData.filter(x=>x.state==='closed').length,uncertain=faceData.filter(x=>x.state==='uncertain').length;return{index,file,url,faces:faces.length,closed,uncertain,sharp,clip:exposure(ctx),faceData}}
function normalize(items,key){const vals=items.map(x=>x[key]).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals);for(const x of items)x[key+'N']=max>min?(x[key]-min)/(max-min):.5}
function scoreAll(arr){const maxFaces=Math.max(...arr.map(x=>x.faces));normalize(arr,'sharp');for(const x of arr)x.score=(x.faces===maxFaces?1000:-260*(maxFaces-x.faces))-x.closed*180-x.uncertain*55+x.sharpN*70-Math.min(.25,x.clip)*120;arr.sort((a,b)=>b.score-a.score);return arr}
function meta(x,rank){const eye=x.faces?`${x.closed?`${x.closed} 人闭眼`:'没有明显闭眼'}${x.uncertain?` · ${x.uncertain} 人眼睛不确定`:''}`:'没识别到人脸';return`${x.faces} 人 · ${eye} · 清晰度 ${rank}`}
function render(){const w=items[0];winnerImg.src=w.url;winnerName.textContent=w.file.name;winnerMeta.textContent=meta(w,'第 1');list.innerHTML=items.map((x,i)=>`<button type="button" data-i="${i}" class="shot ${i===0?'winner':''}"><img src="${x.url}" alt=""><span><strong>${i===0?'建议留这张':`第 ${i+1}`}</strong><small>${x.faces} 人 · ${x.closed?`${x.closed} 人闭眼`:'无明显闭眼'}${x.uncertain?` · ${x.uncertain} 不确定`:''}</small></span><em>${i===0?'✓':''}</em></button>`).join('');list.querySelectorAll('.shot').forEach(b=>b.onclick=()=>{const x=items[Number(b.dataset.i)];winnerImg.src=x.url;winnerName.textContent=x.file.name;winnerMeta.textContent=meta(x,`第 ${Number(b.dataset.i)+1}`);window.scrollTo({top:0,behavior:'smooth'})})}
async function openFiles(files){const fs=[...files].filter(f=>f.type.startsWith('image/'));if(fs.length<2){setError('至少选两张照片。');return}if(fs.length>20){setError('一次先选 2–20 张。');return}setError('');cleanUrls();intro.hidden=true;busy.hidden=false;result.hidden=true;try{await loadLandmarker();const out=[];for(let i=0;i<fs.length;i++){busyText.textContent=`正在看第 ${i+1} / ${fs.length} 张`;out.push(await analyze(fs[i],i))}items=scoreAll(out);busy.hidden=true;result.hidden=false;render();window.scrollTo({top:0,behavior:'instant'})}catch(e){console.error(e);busy.hidden=true;intro.hidden=false;setError('这些照片没有成功分析。')}}
pick.onclick=()=>filesInput.click();filesInput.onchange=()=>{openFiles(filesInput.files);filesInput.value=''};again.onclick=()=>filesInput.click();back.onclick=()=>{result.hidden=true;busy.hidden=true;intro.hidden=false;cleanUrls();items=[];window.scrollTo({top:0,behavior:'instant'})};
share.onclick=async()=>{const w=items[0];if(!w)return;try{if(navigator.canShare?.({files:[w.file]}))await navigator.share({files:[w.file],title:'合照挑一张'});else if(navigator.share)await navigator.share({title:'合照挑一张',text:`建议留：${w.file.name}`})}catch{}};
window.addEventListener('pagehide',cleanUrls);
})();