(() => {
  const $ = (s) => document.querySelector(s);
  const photo = $('#photo'), stage = $('#photoStage'), markerLayer = $('#markerLayer'), stepLabel = $('#stepLabel'), stepTitle = $('#stepTitle'), stepMeta = $('#stepMeta'), note = $('#workNote'), recal = $('#recalibrate');
  if (!photo || !stage || !markerLayer) return;
  let map = null, checkedKey = '', resetting = false;
  function build(){if(!photo.naturalWidth)return;const max=700,s=Math.min(1,max/Math.max(photo.naturalWidth,photo.naturalHeight)),w=Math.max(2,Math.round(photo.naturalWidth*s)),h=Math.max(2,Math.round(photo.naturalHeight*s)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(photo,0,0,w,h);const d=x.getImageData(0,0,w,h).data,g=new Uint8Array(w*h),m=new Float32Array(w*h),v=[];for(let i=0,p=0;i<d.length;i+=4,p++)g[p]=.299*d[i]+.587*d[i+1]+.114*d[i+2];for(let y=1;y<h-1;y++)for(let xx=1;xx<w-1;xx++){const i=y*w+xx,gx=-g[i-w-1]-2*g[i-1]-g[i+w-1]+g[i-w+1]+2*g[i+1]+g[i+w+1],gy=-g[i-w-1]-2*g[i-w]-g[i-w+1]+g[i+w-1]+2*g[i+w]+g[i+w+1],q=Math.hypot(gx,gy);m[i]=q;if((xx+y)%9===0)v.push(q)}v.sort((a,b)=>a-b);map={w,h,m,th:Math.max(65,v[Math.floor(v.length*.8)]||65),sx:photo.naturalWidth/w,sy:photo.naturalHeight/h}}
  function pts(){return [...markerLayer.querySelectorAll('.marker')].slice(0,4).map(n=>({x:parseFloat(n.style.left)/100*photo.naturalWidth,y:parseFloat(n.style.top)/100*photo.naturalHeight})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))}
  function support(a,b){if(!map)return 1;const ax=a.x/map.sx,ay=a.y/map.sy,bx=b.x/map.sx,by=b.y/map.sy,dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;let ok=0;for(let k=1;k<=28;k++){const t=k/29,cx=ax+dx*t,cy=ay+dy*t;let best=0;for(let o=-2;o<=2;o++){const x=Math.round(cx+nx*o),y=Math.round(cy+ny*o);if(x>0&&y>0&&x<map.w-1&&y<map.h-1)best=Math.max(best,map.m[y*map.w+x])}if(best>map.th*.68)ok++}return ok/28}
  function validate(){if(resetting||stepLabel.textContent!=='开始测量'||!map)return;const p=pts();if(p.length!==4)return;const key=p.map(q=>`${q.x.toFixed(0)},${q.y.toFixed(0)}`).join('|');if(key===checkedKey)return;checkedKey=key;const s=(support(p[0],p[1])+support(p[1],p[2])+support(p[2],p[3])+support(p[3],p[0]))/4;if(s<.14){resetting=true;recal?.click();resetting=false;stepTitle.textContent='参考外框没有贴准';stepMeta.textContent='未采用';note.textContent='这四条边没有贴住同一个参考物外框，所以没有计算。点一下卡片或 A4 纸中间再试。'}}
  photo.addEventListener('load',()=>{checkedKey='';setTimeout(build,30)});
  new MutationObserver(()=>setTimeout(validate,25)).observe(markerLayer,{childList:true});
})();