(() => {
  const $ = (s) => document.querySelector(s);
  const stage = $('#photoStage'), photo = $('#photo'), stepLabel = $('#stepLabel'), stepTitle = $('#stepTitle'), stepMeta = $('#stepMeta'), note = $('#workNote'), recal = $('#recalibrate'), undo = $('#undo');
  if (!stage || !photo) return;
  let edge = null, touch = null, cvPromise = null, applying = false;
  const ratioFor = () => document.querySelector('[data-ref].active')?.dataset.ref === 'a4' ? 297 / 210 : 85.6 / 53.98;
  const titleFor = () => document.querySelector('[data-ref].active')?.dataset.ref === 'a4' ? 'A4 纸' : '卡片';
  const calibrated = () => stepLabel.textContent === '开始测量';
  const loupe = document.createElement('div'); loupe.className='measure-loupe'; loupe.hidden=true; loupe.innerHTML='<canvas width="180" height="180"></canvas><i></i>'; document.body.append(loupe); const lctx=loupe.querySelector('canvas').getContext('2d');
  function loadScript(src, timeout=6500){return new Promise(r=>{const s=document.createElement('script');let done=false;const end=v=>{if(done)return;done=true;clearTimeout(t);if(!v)s.remove();r(v)};const t=setTimeout(()=>end(false),timeout);s.async=true;s.src=src;s.onload=()=>end(true);s.onerror=()=>end(false);document.head.append(s)})}
  async function ensureCv(){if(window.cv?.Mat)return window.cv;if(cvPromise)return cvPromise;cvPromise=(async()=>{for(const src of ['https://docs.opencv.org/4.x/opencv.js','https://cdn.jsdelivr.net/npm/@techstark/opencv-js@4.10.0-release.1/dist/opencv.js']){if(await loadScript(src)){for(let i=0;i<80;i++){if(window.cv?.Mat)return window.cv;await new Promise(r=>setTimeout(r,100))}}}return null})();return cvPromise}
  function buildEdge(){const max=900,sc=Math.min(1,max/Math.max(photo.naturalWidth,photo.naturalHeight)),w=Math.max(2,Math.round(photo.naturalWidth*sc)),h=Math.max(2,Math.round(photo.naturalHeight*sc)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(photo,0,0,w,h);const p=ctx.getImageData(0,0,w,h).data,g=new Uint8Array(w*h),m=new Float32Array(w*h);for(let i=0,j=0;i<p.length;i+=4,j++)g[j]=Math.round(.299*p[i]+.587*p[i+1]+.114*p[i+2]);const vals=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,gx=-g[i-w-1]-2*g[i-1]-g[i+w-1]+g[i-w+1]+2*g[i+1]+g[i+w+1],gy=-g[i-w-1]-2*g[i-w]-g[i-w+1]+g[i+w-1]+2*g[i+w]+g[i+w+1],v=Math.hypot(gx,gy);m[i]=v;if((x+y)%7===0)vals.push(v)}vals.sort((a,b)=>a-b);const th=Math.max(70,vals[Math.floor(vals.length*.82)]||70);edge={w,h,m,th,sx:photo.naturalWidth/w,sy:photo.naturalHeight/h}}
  function snap(pt,corner=false){if(!edge)return pt;const x0=pt.x/edge.sx,y0=pt.y/edge.sy,rect=stage.getBoundingClientRect(),rad=Math.max(4,Math.round((corner?20:13)/Math.max(1,rect.width)*edge.w));let best=null,score=0;for(let y=Math.max(1,Math.floor(y0-rad));y<=Math.min(edge.h-2,Math.ceil(y0+rad));y++)for(let x=Math.max(1,Math.floor(x0-rad));x<=Math.min(edge.w-2,Math.ceil(x0+rad));x++){const v=edge.m[y*edge.w+x]*(1-.42*Math.min(1,Math.hypot(x-x0,y-y0)/rad));if(v>score){score=v;best={x,y}}}return best&&score>edge.th*.72?{x:best.x*edge.sx,y:best.y*edge.sy}:pt}
  function nat(e){const r=stage.getBoundingClientRect();return{x:Math.max(0,Math.min(photo.naturalWidth,(e.clientX-r.left)/r.width*photo.naturalWidth)),y:Math.max(0,Math.min(photo.naturalHeight,(e.clientY-r.top)/r.height*photo.naturalHeight))}}
  function client(pt){const r=stage.getBoundingClientRect();return{x:r.left+pt.x/photo.naturalWidth*r.width,y:r.top+pt.y/photo.naturalHeight*r.height}}
  function dispatch(pt){const c=client(pt);stage.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true,pointerType:'touch',clientX:c.x,clientY:c.y,isPrimary:true}))}
  function showLoupe(pt){const s=Math.max(26,Math.round(Math.min(photo.naturalWidth,photo.naturalHeight)*.018)),x=Math.max(0,Math.min(photo.naturalWidth-s,pt.x-s/2)),y=Math.max(0,Math.min(photo.naturalHeight-s,pt.y-s/2));lctx.imageSmoothingEnabled=false;lctx.clearRect(0,0,180,180);lctx.drawImage(photo,x,y,s,s,0,0,180,180);loupe.hidden=false}
  function order(q){const cx=q.reduce((s,p)=>s+p.x,0)/4,cy=q.reduce((s,p)=>s+p.y,0)/4,a=[...q].sort((p,n)=>Math.atan2(p.y-cy,p.x-cx)-Math.atan2(n.y-cy,n.x-cx));let k=0,v=1e9;a.forEach((p,i)=>{if(p.x+p.y<v){v=p.x+p.y;k=i}});return a.slice(k).concat(a.slice(0,k))}
  function side(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
  function chooseQuad(cv,src){const target=ratioFor(),gray=new cv.Mat(),blur=new cv.Mat(),can=new cv.Mat(),contours=new cv.MatVector(),hier=new cv.Mat();cv.cvtColor(src,gray,cv.COLOR_RGBA2GRAY);cv.GaussianBlur(gray,blur,new cv.Size(5,5),0);let best=null;for(const low of [45,75,110]){cv.Canny(blur,can,low,low*2.4);cv.findContours(can,contours,hier,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE);for(let i=0;i<contours.size();i++){const cnt=contours.get(i),peri=cv.arcLength(cnt,true),poly=new cv.Mat();cv.approxPolyDP(cnt,poly,.025*peri,true);if(poly.rows===4&&cv.isContourConvex(poly)){const area=Math.abs(cv.contourArea(poly)),frac=area/(src.cols*src.rows);if(frac>.008&&frac<.62){const q=[];for(let j=0;j<4;j++)q.push({x:poly.intPtr(j,0)[0],y:poly.intPtr(j,0)[1]});const o=order(q),s=[side(o[0],o[1]),side(o[1],o[2]),side(o[2],o[3]),side(o[3],o[0])],ra=Math.max((s[0]+s[2])/2,(s[1]+s[3])/2)/Math.max(1,Math.min((s[0]+s[2])/2,(s[1]+s[3])/2)),err=Math.abs(Math.log(ra/target)),minS=Math.min(...s),score=3*Math.exp(-Math.pow(err/.22,2))+Math.min(1,frac/.05)+Math.min(1,minS/120);if(err<.42&&(!best||score>best.score))best={q:o,score,err,frac,minS}}}poly.delete();cnt.delete()}}gray.delete();blur.delete();can.delete();contours.delete();hier.delete();return best}
  async function autoFind(){if(!photo.naturalWidth||applying)return;buildEdge();stepTitle.textContent='正在找参考物';stepMeta.textContent='';note.textContent='正在检查参考物外框。';const cv=await ensureCv();if(!cv){stepTitle.textContent=`点出${titleFor()}的四个角`;note.textContent='自动找边没有加载成功。手指可以粗略点，端点会自动吸附到附近边缘。';return}try{const src=cv.imread(photo),max=900,sc=Math.min(1,max/Math.max(src.cols,src.rows)),small=new cv.Mat();if(sc<1)cv.resize(src,small,new cv.Size(Math.round(src.cols*sc),Math.round(src.rows*sc)),0,0,cv.INTER_AREA);else src.copyTo(small);const cand=chooseQuad(cv,small);src.delete();small.delete();if(cand&&cand.score>4.15&&cand.minS>95){applying=true;recal.click();const sx=photo.naturalWidth/(Math.round(photo.naturalWidth*sc)),sy=photo.naturalHeight/(Math.round(photo.naturalHeight*sc));cand.q.map(p=>({x:p.x*sx,y:p.y*sy})).forEach(dispatch);applying=false;if(calibrated()){stepMeta.textContent='自动校准';note.textContent=cand.minS/Math.max(sc,.001)>550?'参考已自动找到。当前照片适合精细测量。':'参考已自动找到。想要更高精度，可以把参考物拍得更大。';return}}stepTitle.textContent=`点出${titleFor()}的四个角`;stepMeta.textContent='端点自动吸附';note.textContent='没有可靠找到完整外框。手指只需要粗略点四角，放大镜和边缘吸附会帮你贴准。'}catch{stepTitle.textContent=`点出${titleFor()}的四个角`;note.textContent='自动找边没有完成。手指可以粗略点，端点会自动吸附到附近边缘。'}}
  stage.addEventListener('pointerdown',e=>{if(!e.isTrusted||!photo.naturalWidth)return;e.preventDefault();e.stopImmediatePropagation();const p=nat(e);touch={id:e.pointerId,p};try{stage.setPointerCapture(e.pointerId)}catch{}showLoupe(snap(p,!calibrated()))},true);
  stage.addEventListener('pointermove',e=>{if(!touch||e.pointerId!==touch.id)return;e.preventDefault();touch.p=nat(e);showLoupe(snap(touch.p,!calibrated()))},true);
  stage.addEventListener('pointerup',e=>{if(!touch||e.pointerId!==touch.id)return;e.preventDefault();e.stopImmediatePropagation();const p=snap(nat(e),!calibrated());touch=null;loupe.hidden=true;dispatch(p)},true);
  stage.addEventListener('pointercancel',()=>{touch=null;loupe.hidden=true},true);
  if(undo)undo.textContent='撤销上一步';
  if(recal){const old=recal.onclick;recal.onclick=function(e){if(typeof old==='function')old.call(this,e);if(!applying){stepTitle.textContent=`点出${titleFor()}的四个角`;stepMeta.textContent='端点自动吸附';note.textContent='重新粗略点四角即可。'}}}
  photo.addEventListener('load',()=>setTimeout(autoFind,60));
  document.querySelectorAll('[data-ref]').forEach(b=>b.addEventListener('click',()=>photo.naturalWidth&&setTimeout(autoFind,60)));
})();