(()=>{
'use strict';
const $=s=>document.querySelector(s);
const intro=$('#intro'),startBtn=$('#start'),error=$('#error'),session=$('#session'),result=$('#result');
const cancel=$('#cancel'),finish=$('#finish'),restart=$('#restart'),back=$('#back'),share=$('#share');
const listenState=$('#listenState'),caughtLabel=$('#caughtLabel'),caughtWord=$('#caughtWord'),caughtCount=$('#caughtCount'),lastHeard=$('#lastHeard');
const repeatFlash=$('#repeatFlash'),repeatFlashWord=$('#repeatFlashWord'),ranking=$('#ranking'),utteranceCount=$('#utteranceCount'),timeEl=$('#time'),heard=$('#heard'),pulse=$('#pulse');
const resultTop=$('#resultTop'),resultMeta=$('#resultMeta'),resultList=$('#resultList');
const langButtons=[...document.querySelectorAll('[data-lang]')];
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const segmenterCache={};
const ZH=[['嗯','填充词'],['呃','填充词'],['额','填充词'],['啊','填充词'],['那个','填充词'],['就是说','接续词'],['就是','接续词'],['然后','接续词'],['然后呢','接续词'],['所以','接续词'],['所以说','接续词'],['其实','起手式'],['实际上','起手式'],['事实上','起手式'],['基本上','起手式'],['反正','起手式'],['我觉得','起手式'],['我认为','起手式'],['我想','起手式'],['怎么说','起手式'],['怎么讲','起手式'],['可能','缓冲词'],['应该','缓冲词'],['好像','缓冲词'],['有点','缓冲词'],['有一点','缓冲词'],['对吧','尾巴词'],['是吧','尾巴词'],['你懂吧','尾巴词'],['你知道','尾巴词']];
const EN=[['um','filler'],['uh','filler'],['erm','filler'],['like','filler'],['you know','tail'],['i mean','starter'],['i think','starter'],['i feel','starter'],['actually','starter'],['basically','starter'],['honestly','starter'],['literally','buffer'],['probably','buffer'],['maybe','buffer'],['kind of','buffer'],['sort of','buffer'],['so','connector'],['and then','connector'],['then','connector'],['but','connector'],['well','starter'],['right','tail'],['okay','tail'],['you see','tail']];
const ZH_STOP=new Set(['的','了','是','我','你','他','她','它','我们','你们','他们','这个','那个','这些','那些','一个','一种','一下','一些','什么','怎么','为什么','可以','能够','没有','不是','还有','或者','如果','那么','就','也','都','在','有','和','跟','与','而','而且','把','被','让','给','对','从','到','上','下','里','外','中','会','要','很','太','更','最','比较','非常','这样','那样','这里','那里','现在','今天','时候','东西','事情']);
const EN_STOP=new Set(['the','a','an','i','you','he','she','it','we','they','this','that','these','those','is','are','was','were','be','been','being','have','has','had','do','does','did','can','could','will','would','should','may','might','and','or','but','if','then','to','of','in','on','at','for','from','with','as','by','about','very','really','just','also','there','here']);
const TYPE_ZH={filler:'填充词',connector:'接续词',starter:'起手式',buffer:'缓冲词',tail:'尾巴词',repeat:'重复词','填充词':'填充词','接续词':'接续词','起手式':'起手式','缓冲词':'缓冲词','尾巴词':'尾巴词'};
let langMode=localStorage.getItem('repeat-lang-v2')||'auto',inferredLang=null;
let rec=null,wanted=false,generation=0,restartTimer=0,starting=false,startedAt=0,timer=0,utterances=[],latest=[],lastFlashAt=0,lastInterim='';
const clean=s=>String(s||'').normalize('NFKC').replace(/[，。！？、,.!?；;：:“”‘’"'（）()\[\]【】]/g,' ').replace(/\s+/g,' ').trim();
const compact=s=>clean(s).replace(/\s+/g,'');
const fmtTime=ms=>{const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60;return`${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`};
const elapsed=()=>Math.max(1,Date.now()-startedAt);
function setError(t=''){error.hidden=!t;error.textContent=t}
function detectLang(text){const cjk=(text.match(/[\u3400-\u9fff]/g)||[]).length,latin=(text.match(/[A-Za-z]/g)||[]).length;return cjk>=Math.max(2,latin*.45)?'zh':latin>=3?'en':null}
function langCode(){if(langMode==='zh')return'zh-CN';if(langMode==='en')return'en-US';if(inferredLang==='zh')return'zh-CN';if(inferredLang==='en')return'en-US';return /^zh/i.test(navigator.language||'')?'zh-CN':'en-US'}
function syncLang(){langButtons.forEach(b=>b.classList.toggle('active',b.dataset.lang===langMode));try{localStorage.setItem('repeat-lang-v2',langMode)}catch{}}
function segmenter(lang){const k=lang==='en'?'en-US':'zh-CN';if(!segmenterCache[k]&&Intl?.Segmenter)segmenterCache[k]=new Intl.Segmenter(k,{granularity:'word'});return segmenterCache[k]}
function wordsOf(text,lang){const seg=segmenter(lang);if(seg){const out=[];for(const x of seg.segment(text)){if(x.isWordLike===false)continue;const w=clean(x.segment).toLowerCase();if(w&&!/^\d+$/.test(w))out.push(w)}return out}return lang==='en'?clean(text).toLowerCase().split(/\s+/).filter(Boolean):[...compact(text)]}
function countNeedle(hay,needle,lang){if(lang==='en'){const h=` ${clean(hay).toLowerCase()} `,n=` ${needle.toLowerCase()} `;let c=0,i=0;while((i=h.indexOf(n,i))>=0){c++;i+=n.length}return c}let c=0,i=0,h=compact(hay);while((i=h.indexOf(needle,i))>=0){c++;i+=Math.max(1,needle.length)}return c}
function add(map,phrase,type,idx,count=1,pos='middle'){phrase=clean(phrase).toLowerCase();if(!phrase||phrase.length>24)return;let x=map.get(phrase);if(!x){x={phrase,count:0,utter:new Set(),type,pos:{start:0,middle:0,end:0}};map.set(phrase,x)}x.count+=count;x.utter.add(idx);x.pos[pos]=(x.pos[pos]||0)+count;if(type!=='repeat')x.type=type}
function analyze(){const map=new Map();utterances.forEach((u,idx)=>{const lang=u.lang||detectLang(u.text)||'zh',text=clean(u.text),low=text.toLowerCase(),dict=lang==='en'?EN:ZH;for(const [phrase,type] of dict){const n=countNeedle(text,phrase,lang);if(!n)continue;const normalized=lang==='en'?low.trim():compact(text),p=lang==='en'?phrase.toLowerCase():phrase;let pos='middle';if(normalized.startsWith(p))pos='start';else if(normalized.endsWith(p))pos='end';add(map,phrase,type,idx,n,pos)}const ws=wordsOf(text,lang).filter(w=>w.length>=2&&w.length<=10&&!(lang==='en'?EN_STOP:ZH_STOP).has(w));for(const w of ws)add(map,w,'repeat',idx,1,'middle');for(let i=0;i<ws.length-1;i++){const p=lang==='en'?`${ws[i]} ${ws[i+1]}`:`${ws[i]}${ws[i+1]}`;if(p.length<=(lang==='en'?22:12))add(map,p,'repeat',idx,1,'middle')}});let arr=[...map.values()].filter(x=>x.type==='repeat'?(x.count>=3&&x.utter.size>=2):(x.count>=2&&x.utter.size>=2));arr.forEach(x=>{const habit=x.type!=='repeat';x.score=x.count+x.utter.size*.9+(habit?4.2:0)+(x.pos.start>1?1.1:0)+(x.pos.end>1?.7:0);x.rate=x.count/(elapsed()/60000)});arr.sort((a,b)=>b.score-a.score||b.count-a.count);const out=[];for(const x of arr){const dup=out.find(y=>{const a=y.phrase,b=x.phrase;return(a.includes(b)||b.includes(a))&&Math.abs(y.count-x.count)<=1});if(dup){if(x.type!=='repeat'&&dup.type==='repeat'){out[out.indexOf(dup)]=x}continue}out.push(x);if(out.length>=8)break}return out}
function typeLabel(x){return TYPE_ZH[x.type]||'重复词'}
function positionLabel(x){const p=x.pos||{},m=Math.max(p.start||0,p.middle||0,p.end||0);if(m<2)return'';return m===p.start?'常在句首':m===p.end?'常在句尾':'常在中间'}
function rateText(x){const ms=elapsed()/Math.max(1,x.count),s=Math.round(ms/1000);return s<60?`平均每 ${Math.max(1,s)} 秒一次`:`平均每 ${(s/60).toFixed(1)} 分钟一次`}
function renderLive(lastText=''){latest=analyze();const top=latest[0];if(top){caughtLabel.textContent=`${typeLabel(top)} · ${positionLabel(top)||'重复最明显'}`;caughtWord.textContent=top.phrase;caughtCount.textContent=`${top.count} 次 · ${rateText(top)}`}else{caughtLabel.textContent=utterances.length<3?'先正常说一会儿':'还在找习惯';caughtWord.textContent='—';caughtCount.textContent='不会因为出现两次就下结论'}if(lastText)lastHeard.textContent=`刚才听到：${lastText.length>42?lastText.slice(0,42)+'…':lastText}`;ranking.innerHTML=latest.length?latest.slice(0,5).map((x,i)=>`<li><i>${String(i+1).padStart(2,'0')}</i><span>${x.phrase}<small>${typeLabel(x)}${positionLabel(x)?' · '+positionLabel(x):''}</small></span><strong>× ${x.count}</strong></li>`).join(''):'<li class="empty">继续正常说。主题词出现很多次，也不会自动当成口头禅。</li>';utteranceCount.textContent=`${utterances.length} 段`;heard.textContent=`${utterances.length} 段`;if(lastText&&top&&top.count>=3&&clean(lastText).toLowerCase().includes(top.phrase.toLowerCase())&&performance.now()-lastFlashAt>1000){lastFlashAt=performance.now();repeatFlashWord.textContent=top.phrase;repeatFlash.hidden=false;clearTimeout(renderLive.flashTimer);renderLive.flashTimer=setTimeout(()=>repeatFlash.hidden=true,850)}}
function makeRec(){if(!SpeechRecognition)return null;const r=new SpeechRecognition();r.lang=langCode();r.continuous=false;r.interimResults=true;r.maxAlternatives=3;return r}
function stopRecognition(){wanted=false;generation++;clearTimeout(restartTimer);restartTimer=0;starting=false;if(rec){rec.onend=rec.onerror=rec.onresult=null;try{rec.abort()}catch{}rec=null}pulse.classList.remove('live')}
function schedule(delay=100){if(!wanted||document.hidden)return;const g=generation;clearTimeout(restartTimer);restartTimer=setTimeout(()=>{if(g===generation&&wanted)runSession(g)},delay)}
function runSession(g){if(!wanted||starting||g!==generation||document.hidden)return;starting=true;const r=makeRec();if(!r){starting=false;setError('当前浏览器没有提供可用的语音识别。');return}rec=r;let finished=false,heardFinal=false;const done=(d=100)=>{if(finished)return;finished=true;starting=false;if(rec===r)rec=null;if(wanted&&g===generation)schedule(d)};r.onstart=()=>{starting=false;listenState.textContent=`正在听 · ${langCode()==='en-US'?'EN':'中文'}`};r.onspeechstart=()=>pulse.classList.add('live');r.onspeechend=()=>pulse.classList.remove('live');r.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const res=e.results[i],text=clean(res[0]?.transcript);if(!text)continue;if(res.isFinal){heardFinal=true;lastInterim='';let lang=detectLang(text)||inferredLang||(langCode()==='en-US'?'en':'zh');if(langMode==='auto'&&lang&&!inferredLang){inferredLang=lang;listenState.textContent=`已适配 · ${lang==='en'?'EN':'中文'}`}utterances.push({text,lang});renderLive(text)}else{lastInterim=text;lastHeard.textContent=`正在听：${text.length>42?text.slice(0,42)+'…':text}`}}};r.onerror=e=>{pulse.classList.remove('live');if(['not-allowed','service-not-allowed','audio-capture'].includes(e.error)){wanted=false;listenState.textContent='麦克风未开启';setError('需要允许浏览器使用麦克风和语音识别。');return}if(e.error==='no-speech')done(70);else done(180)};r.onend=()=>{pulse.classList.remove('live');if(!heardFinal&&lastInterim){lastHeard.textContent=`听到了，但这段没有形成稳定文字：${lastInterim.slice(0,32)}`;lastInterim=''}done(heardFinal?70:110)};try{r.start()}catch{done(260)}}
function startRecognition(){if(!SpeechRecognition)throw new Error('unsupported');stopRecognition();wanted=true;generation++;schedule(40)}
function startTimer(){clearInterval(timer);startedAt=Date.now();timeEl.textContent='00:00';timer=setInterval(()=>timeEl.textContent=fmtTime(Date.now()-startedAt),500)}
function showSession(){intro.hidden=true;result.hidden=true;session.hidden=false;utterances=[];latest=[];lastFlashAt=0;lastInterim='';inferredLang=null;repeatFlash.hidden=true;ranking.innerHTML='<li class="empty">继续正常说。主题词出现很多次，也不会自动当成口头禅。</li>';caughtLabel.textContent='先正常说一会儿';caughtWord.textContent='—';caughtCount.textContent='不会因为出现两次就下结论';lastHeard.textContent='会显示浏览器识别到的文字，方便你判断它有没有听准。';utteranceCount.textContent='0 段';heard.textContent='0 段';setError('');startTimer();try{startRecognition()}catch{session.hidden=true;intro.hidden=false;clearInterval(timer);setError('当前浏览器没有提供可用的语音识别。')}}
function renderResult(){latest=analyze();const ms=elapsed(),top=latest[0];resultTop.textContent=top?top.phrase:'没抓到';resultMeta.textContent=top?`${typeLabel(top)} · ${top.count} 次 · ${rateText(top)}${positionLabel(top)?' · '+positionLabel(top):''}`:`${fmtTime(ms)} · 暂时没有足够明显的语言习惯`;resultList.innerHTML=latest.length?latest.slice(0,6).map((x,i)=>`<li><i>${String(i+1).padStart(2,'0')}</i><span>${x.phrase}<small>${typeLabel(x)}${positionLabel(x)?' · '+positionLabel(x):''}</small></span><strong>× ${x.count}</strong></li>`).join(''):'<li><i>—</i><span>这次没有明显重复</span><strong></strong></li>'}
function finishSession(){stopRecognition();clearInterval(timer);session.hidden=true;result.hidden=false;renderResult();window.scrollTo({top:0,behavior:'instant'})}
function cancelSession(){stopRecognition();clearInterval(timer);session.hidden=true;result.hidden=true;intro.hidden=false;window.scrollTo({top:0,behavior:'instant'})}
function shareText(){const list=latest.slice(0,5);const text=list.length?`我刚才最明显的口语习惯：${list.map(x=>`${x.phrase} × ${x.count}`).join('、')}`:'我刚才没有抓到明显口头禅。';if(navigator.share){navigator.share({title:'口头禅',text}).catch(()=>{})}else if(navigator.clipboard){navigator.clipboard.writeText(text).then(()=>{share.textContent='已复制';setTimeout(()=>share.textContent='分享结果',900)}).catch(()=>{})}}
langButtons.forEach(b=>b.onclick=()=>{langMode=b.dataset.lang;inferredLang=langMode==='auto'?null:langMode;syncLang();if(!session.hidden&&wanted)startRecognition()});startBtn.onclick=showSession;finish.onclick=finishSession;cancel.onclick=cancelSession;restart.onclick=showSession;back.onclick=cancelSession;share.onclick=shareText;document.addEventListener('visibilitychange',()=>{if(session.hidden)return;if(document.hidden){stopRecognition();listenState.textContent='已暂停'}else{try{startRecognition()}catch{}}});window.addEventListener('pagehide',()=>{stopRecognition();clearInterval(timer)});syncLang();
})();